filecoin-project/go-f3

adversary/absent.go, adversary/equiv.go, f3/api.go, f3/granite.go, f3/participant.go, sim/network.go
=> Implemented signing paylaods in terms of abstract signer

adversary/absent.go, adversary/equiv.go, f3/api.go, f3/granite.go, f3/participant.go, sim/sim.go
=> Implement receiving new EC-compatible chains

f3/vrf.go, sim/sim.go
=> VRF implementation (#6)

LICENSE-APACHE, LICENSE-MIT, README.md
* Updates readme 
* Licence
* Structure
* Link to FIP for context (latest commit, to be replace with main when merged)
* Adds license files (MIT + Apache)
=> Update readme and add license

adversary/absent.go, adversary/equiv.go, f3/api.go, f3/chain.go, f3/granite.go, f3/participant.go, f3/powertable.go, f3sim.go, sim/network.go, sim/sim.go, test/absent_test.go, test/equiv_test.go, test/honest_test.go
=> Replace panics with errors

adversary/equiv.go, f3/granite.go, f3/participant.go
=> Use numbers for phases instead of names

f3/granite.go
Implicit justification is not a thing in the code/spec, just an idea.
=> Remove comments about implicit justification

f3/api.go, f3/granite.go
=> Optimize justification creation

adversary/withhold.go, f3/api.go, f3/granite.go, f3/types.go, sim/network.go
This reverts commit 8511a0d111642dc26b9a9e67d036bed7ece561b4.
=> Revert "Move network name into a host API function. (#80)"

adversary/withhold.go, f3/granite.go
@Kubuxu as discussed in Slack, message justification is now nullable.
=> Make GMessage justification optional, clean up some control flow for it.

adversary/withhold.go, f3/api.go, f3/granite.go, f3/types.go, sim/network.go
=> Move network name into a host API function.

sim/network.go, sim/sim.go
Closes #26 (it should already be closed from before? see my comment on the issue itself).
=> Include network name in Network struct

f3/granite.go, f3/vrf.go
=> Include DST and NetworkName in VRF signing

f3/granite.go, f3sim.go, test/constants.go
Rolls forward accidental merge #82
=> Simplify synchronization of participants to simple exponential back-off

adversary/withhold.go, f3/api.go, f3/chain.go, f3/granite.go, f3sim.go, sim/latency.go, sim/network.go, sim/sim.go, test/constants.go, test/withhold_test.go
=> Use time.Time() instead of float64

cmd/f3sim/f3sim.go, gpbft/gpbft.go, test/constants.go
Meaning of delta now matches FIP.
=> Change semantics of delta parameter to be a bound on message delay

gpbft/gpbft.go
This expression of the justification rules is easier to mentally check, and ensures that every field of the justification is always checked.
=> Express message justification rules as data rather than procedural code

adversary/decide.go, gpbft/gpbft.go, test/decide_test.go
=> Nodes decide on strong quorum of DECIDE regardless of phase

adversary/absent.go, adversary/decide.go, adversary/withhold.go, cmd/f3sim/f3sim.go, gpbft/api.go, gpbft/participant.go, sim/ec.go, sim/sim.go, test/absent_test.go, test/decide_test.go, test/honest_test.go, test/withhold_test.go
Work towards #27. 
The step after this is for the participant to pull another chain after completing each instance.
=> Change API so participant pulls canonical chain when starting

cmd/f3sim/f3sim.go
Previously set delta of 2ns, but mean latency of 500ms.
=> Fix initialisation of delta from f3sim main

go.mod, go.sum
=> chore: update kyber to released version

sim/adversary/absent.go, sim/adversary/api.go, sim/adversary/decide.go, sim/adversary/repeat.go, sim/adversary/withhold.go, sim/network.go, sim/sim.go
Consolidate adversary APIs into their own package and address review comments raised in #156.
=> Move adversary APIs and type assert

gpbft/gpbft.go
=> Implement skipping directly to DECIDE phase on receiving a valid (justified) DECIDE message.

gpbft/chain.go
=> Limit max chain length to 100 tipsets

gpbft/api.go, gpbft/options.go
For #192.
Specified in https://github.com/filecoin-project/FIPs/pull/996
=> Change delta backoff to 2.0

Makefile
I've run out of memory when running 60s fuzzing
=> Reduce GOGC while fuzzing

certs/certs.go
Address the stand-alone changes from https://github.com/filecoin-project/go-f3/pull/266#pullrequestreview-2089396736.
=> Address finality certificate nits from #266

sim/ec.go
Simulation checks if an instance is complete (i.e. expected participants has reached some decision) at every network tick. Prior to the changes here this was determined using the number of decisions received.
A problem with this approach is that when some adversary targets are excluded from consensus check a simulation instance may deemed to be complete despite non-targeted participants not having reached a decision yet.
The changes here explicitly checks the ID of participants to assure that only decisions from intended participants are counted towards the total number of expected decisions.
=> Verify decider identity when checking if sim instance is complete

sim/host.go, sim/sim.go
In scenarios where there is partial connectivity among participants it is possible for some participants to receive justification to terminate an instance and start the next before other participants have received such justification.
This can cause a false-negative failure of a simulation. EC stabilisation delay in simulation is a way to mitigate such failures but since it is an absolute time it cannot entirely avoid the problem as it depends on the latency model (among other factors).
The changes here avoid this issue entirely by optimistically starting the next instance when a `simHost` decides earlier than other nodes. The simulation `Run` event loop is then modified to check if the next instance is started already, and if so its base chain matches the general network consensus. This …
=> Allow optimistic early instance start in simulation

cmd/f3/run.go, f3.go, go.mod, go.sum, host.go, manifest.go
=> Move initial instance to manifest

gpbft/chain.go, gpbft/chain_test.go, host.go
Resolves https://github.com/filecoin-project/go-f3/issues/371
=> Implement backoff on base decisions

host.go
=> Implement the head offset

cmd/f3/manifest.go
For operational convenience add support to specify the bootstrap addrs via file, similar to *.pi files in lotus repo.
=> Add support for specifying manifest server bootstrap addrs from file

certstore/certstore.go, cmd/f3/main.go
Fix typo in error message and resolve minor lint warning.
=> Fix typo in sentinel error

gpbft/gpbft_test.go
Test that upon receiving a DECIDE message form a participant with majority power, immediately decides the justified value.
Part of #9
=> Test GPBFT skips to decide

certexchange/polling/common_test.go, certexchange/polling/poller_test.go, certexchange/polling/subscriber_test.go
This tries to produce certificates at a reliable interval so we can accurately measure how "good" our predictions are.
=> Improve subscriber test reliability

host.go
This matches the behavior of certificate verification.
=> Use the correct payload marshaler in the F3 module

certexchange/polling/poller.go, certexchange/polling/poller_test.go, certexchange/polling/subscriber.go, certexchange/polling/subscriber_test.go, certexchange/protocol_test.go, certexchange/server.go, f3.go, manifest/manifest.go, manifest/manifest_test.go, test/f3_test.go
I've also changed the finality exchange start/stop methods to take contexts for consistency.
=> Integrate finality exchange

README.md
Update the README with the most up-to-date state of the project to avoid misleading visitors. Future PRs will add additional documentations and godoc on how to use the APIs, run simulations, etc.
[Rendered](https://github.com/filecoin-project/go-f3/blob/masih/update-readme/README.md)
=> Update readme with the current state of the project

gpbft/gpbft_test.go
Add unit tests that assert the honest participant disregards equivocating messages during an instance execution or at the time of dequeueing messages from future rounds.
Part of #9
=> Test equivocations are ignored current and future instances

sim/adversary/decide.go, test/decide_test.go
- Invalid bitfield
- Participant without power
Part of #235
=> Test bad justification: no power and invalid bitfield

gpbft/gpbft.go, sim/adversary/decide.go, test/decide_test.go
And add a few more justification tests.
=> Check that justification supplemental data matches the vote

gpbft/gpbft_test.go
Test that the participant exists Prepare phase if quorum is not possible, without the need for receiving any further messages or alarm.
Part of #9
=> Test immediate progress from Prepare when quorum is not possible

gpbft/metrics.go, gpbft/participant.go
Add metrics that count the number of errors returned by the exported API.
=> Add metrics for error counts tagged by type

gpbft/vrf.go
`MakeTicket` is not used anywhere; drop it.
=> Remove unused `MakeTicket` function

test/f3_test.go
See https://github.com/filecoin-project/go-f3/issues/460
=> Disable TestFailRecover

emulator/driver.go, f3.go, gpbft/gpbft.go, gpbft/message_builder.go, gpbft/message_builder_test.go, sim/adversary/decide.go, sim/adversary/repeat.go, sim/adversary/spam.go, sim/adversary/withhold.go
Consistently use the American English spelling for the term "marshaler".
=> Use consistent spelling for "marshaler"

emulator/driver_assertions.go, emulator/instance.go, gpbft/gpbft_test.go
Implement message validation unit tests to hit specific justification conditions.
Part of #9
=> Implement additional message validation unit tests

ec/ec.go, ec/fake_ec.go, ec/fake_ec_test.go, go.mod, host.go, metrics.go
We will end up proposing base which will trigger backoff, giving us chance to re-boostrap,
Also added a metric for it.
=> Gracefully handle EC diverging from F3

sim/adversary/decide.go, sim/signing/fake.go, test/signing_suite_test.go
=> Slightly improve aggregation test suite

cmd/f3/run.go, f3.go, manifest/dynamic_manifest.go, manifest/dynamic_manifest_test.go, manifest/manifest.go, test/f3_test.go
- Save latest manifest to datastore
- Add protocol version to manifest
=> Manifest enhancements

certexchange/client.go, certexchange/protocol_test.go, f3.go, manifest/manifest.go, store.go
=> Try to fetch inital power table if specified

test/f3_test.go
Fix minor typos and remove redundant type casts and unused vars.
=> Fix typos in f3 tests and remove redundant code

cmd/f3/manifest.go
Periodically reload the bootrstappers file if present and reconnect to them. This means even if bootstappers change manifest server would keep working.
=> Periodically connect to bootstrappers in manifest server

codecov.yml
And only set a CI status on pull requests, not branches (nothing on main).
=> configure code cov threshold

certexchange/polling/poller.go, certexchange/polling/subscriber.go
If we end up polling for certificates at approximately same time we receive them from GPBFT, add a one-time delay to our timer. This won't affect our predicted interval, but will prevent us from racing with GPBFT for every certificate.
This will solve the issue @Kubuxu was seeing, but it'll still be a bit trigger happy if we're participating in GPBFT (e.g., due to instance duration variance). So, I'm posting this PR (it's still useful regardless) but I want to try something different: let the user configure how many instances they want to lag by. For clients participating in GPBFT, the answer is something less than the power lookback, where 2-5 is probably a good number. For clients not participating in GPBFT, the answer is 0.
=> Offset the predicted CX interval if we align with the GPBFT interval

blssig/aggregation.go, blssig/cache_test.go, blssig/verifier.go
This can save quite a bit of CPU time.
fixes #542
=> Cache decompressed points

gpbft/gpbft.go, gpbft/metrics.go
Add additional metrics to measure progress of GPBFT such that it does not depend on termination of an instance. This provides better visibility into cases where an instance takes longer than expected to terminate or is stuck.
While at it, count the number of times GPBFT either skips to round or skips to decide.
Fixes #540
=> Measure current instance, phase and round change regardless of consensus

f3.go, internal/measurements/attributes.go, internal/measurements/datastore.go, manifest/dynamic_manifest_provider.go
Add metrics that measure all data store interactions caused by F3; these components are:
* ohshitstore
* certstore
* manifest
Fixes #160
=> Add metrics for all F3 datastore interactions

gpbft/gpbft.go, gpbft/gpbft_test.go
To improve censorship resistance and avoid lack of progress due to partially disseminated QUALITY messages include them in rebroadcast.
Part of #591
=> Include QUALITY messages in rebroadcast

gpbft/chain.go, gpbft/gpbft.go
Based on recommendations of Least Authority
=> Select next best converge value compatible with our candidate set

gpbft/gpbft_test.go, gpbft/participant.go
=> Propagate DECIDE messages from the previous instance

gpbft/gpbft.go
Power table argument is not used; remove it.
=> Remove unused argument in find best ticket proposal

gpbft/gpbft.go
A `COMMIT` message may arrive at any round/phase. Regardless, it is handled by `tryCommit`. Refactor the logic of this function such that:
* rebroadcast at `COMMIT` is only attempted if the instance is indeed at that phase and its corresponding round.
* logic is easier to read with definitive switch cases, where each case is commented.
Fixes #593
=> On `tryCommit` only rebroadcast at current round / phase

test/spam_test.go
Add fuzzing for the spam adversary test.
Fixes #340
=> Fuzz spam adversary test

gpbft/gpbft_test.go
Expand validation test cases with invalid justification, specifically:
* unexpected value
* unexpected phase
* justification for bottom
Fixes #237
=> Test additional cases for invalid justification

gpbft/gpbft_test.go
Test a scenario where the power is split exactly 1/3:2/3 across two participants, i.e. the quorum boundaries, and assert that:
* instance progresses to decision with messages from participant with 2/3 power alone.
* instance does not progress without them.
Part of #9
=> Test exact 1/3:2/3 power split

gpbft/gpbft_test.go
Test that late arriving commit from future round with sufficient evidence immediately produces a decision.
Part of #9
=> Test uneven power distribution with late arriving COMMIT

f3_test.go
=> Fix F3 lookback test by advancing time

f3_test.go
This refactors the F3 tests to make them work a bit more reliably. Specifically:
1. It ensures that the initial manfest given to the F3 nodes and the initial manifest given to the dynamic manifest server are the same to avoid a spurious update.
2. It fixes the network names.
3. It switches to a builder pattern (ish) for defining test setups. This will help me  in a test I'm currently writing.
=> Refactor F3 tests

f3.go, f3_test.go
This was causing some testing issues because, e.g., calls to `IsRunning` would block while the startup logic was fetching the initial power table.
=> Avoid holding the F3 lock while starting it

f3_test.go
=> Fix TestF3LateBootstrap flake

f3_test.go
I'm hoping this will fix the flakiness, this part of the test really shouldn't fail and I think the issue is that we're using mock clocks and F3 is just getting too far behind.
=> TestF3LateBootstrap: don't let F3 get too far behind

version.json
=> Bump version in prep to release `v0.4.0`

f3_test.go, internal/gnark/suite_test.go
Fix missing error check in tests.
=> Fix missing error check in tests

host.go
WAL keeps track of all the messages and we cache messages from the latest instance for rebroadcast purposes.
Before starting a new instance, if there are any messages from self for that instance feed them to the participant. That should speed up catch up at that round and effectively aid resume progress for the participant.
Fixes #679
=> Resume instance by sending messages from self

version.json
* Rebroadcast from WAL.
* Resume via WAL.
* FusingManifestProvider fixes.
=> Release 0.5.0

version.json
=> Bump version file to 0.6.0

gpbft/gpbft_test.go
See existing:
https://github.com/filecoin-project/go-f3/blob/b7576c867c0289f29ef04a7bb5126cac08b30423/gpbft/gpbft_test.go#L1451-L1461
=> Remove duplicate test for DECIDE with non-zero round

gen/main.go
Run cbor gen in parallel for faster generation.
=> Run cbor gen in parallel

gpbft/chain.go, gpbft/chain_test.go
Return false if chains of same length are not equal and assert assert it in unit tests.
=> Fix chain comparison bug and add tests

version.json
Make a release to be bubbled up to lotus for 1.30 release.
=> Bump version in prep to release `v0.7.2`

f3.go, internal/powerstore/powerstore.go, internal/powerstore/powerstore_test.go
Cosmetic renaming of the powerstore.
=> Rename OhShitStore™ to `powerstore`

.github/workflows/publish-ghcr.yml
Investigating to see if setting up QEMU would resolve the docker build issues.
Fixes https://github.com/filecoin-project/go-f3/issues/846
=> Set up QEMU prior to image build

chainexchange/options.go, chainexchange/pubsub.go, chainexchange/pubsub_test.go, manifest/manifest.go, manifest/manifest_test.go, partial_msg.go
Resolves https://github.com/filecoin-project/go-f3/issues/875
Unknown JSON fields are ignored by Go's JSON decoder
=> Add chain compression to manifest

observer/options.go, observer/options_test.go
Resolve the given bootstrap addresses to handle dnsaddr gracefully.
=> Handle dnsaddr bootrstrap addresses gracefully

host.go
A node always attempts to get the proposal, for the instance it has not completed yet. This happens even if a node is restarted mid-instance. This is generally OK because the self-equivocation filter would drop any messages with potentially equivocating vote at the time of startup.
The chain broadcast, however, attempts to broadcast the chain as soon as calls to `GetProposal` are made. At that point, there's no message to be filtered through the self-propagation filter. There's just the chain.
To avoid broadcasting chains that are otherwise not useful to other participants, check if there's been any message from self for the instance for which proposal was retrieved. Then only broadcast the chain if there haven't been any prior messages from self, for instance.
Part of #893
=> Check for self messages before chain broadcast on get proposal

gpbft/validator.go, partial_validator.go
=> Wrap failure to get committee for better visibility

cmd/f3/run.go, gpbft/api.go, host.go
=> cleanup: remove handling of SigningMarshaler from f3

gpbft/gpbft.go, gpbft/ticket_rank.go
Also small additional check in linearToExpDist
Resolves #728
=> metrics: report converge participation

gpbft/gpbft.go, gpbft/metrics.go
=> metrics: report chain lengths, cleanup metrics a bit

gpbft/gpbft.go, gpbft/metrics.go
Signed-off-by: Jakub Sztandera <oss@kubuxu.com>
=> metrics: add total power table size metric

gpbft/vrf.go, gpbft/vrf_test.go
Grow the VRF buffer to the appropriate size before writing and add basic tests.
=> Grow VRF buffer before writing and add tests

host.go, observer/observer.go, observer/options.go
Start up observer as part of f3 with some hardcoded settings.
=> Start up observer as part of F3

host.go
A partial message may become complete at the time of validation if there's enough local information about the chain. In which case, convert it back to partial and broadcast it again as part of compensational rebroadcast.
=> Include fulfilled messages in compensational rebroadcast

cmd/f3/aider.go, cmd/f3/main.go, cmd/f3/observer.go, observer/model.go, observer/observer.go, observer/options.go
Increase the default observer subscription buffer size and make it configurable.
---
* Cherry-picked from https://github.com/filecoin-project/go-f3/pull/971
* **Review #985 first.**
=> Increase observer pubsub buffer size

cmd/f3/aider.go, cmd/f3/main.go, cmd/f3/observer.go, observer/model.go, observer/observer.go, observer/options.go
Allow observer to take pubsub as an option along with flag on whether to register validator or not.
---
* Originally implemented across #974 and #976
* Part of #989 
* **Review #987 first.**
=> Allow observer to be integrated into an existing pubsub

bootstrap_delay_test.go, f3.go, tipsettimestamp_test.go
Adds tests for ComputeBoostrapDelay and removes the post bootstrap alignment
especially in tests, it could delay startup of F3
=> test ComputeBoostrapDelay, remove post-bootstrap alignment
