- f3/chain.go
- f3/granite.go
- f3/types.go
- sim/sim.go
Replace CID typedef with a TipSetID struct, opaque wrapping a string (similar to Lotus TipSetKey).
Closes #18
> Implement opaque TipSetKey type.

- f3/granite.go
- f3/participant.go
Extending #29, (new PR as I have no pushing rights on @matejpavlovic 's fork). From @matejpavlovic :
> Resolves #2 .
> 
> Implements the DECIDE phase in Granite.
> As created, this PR is incomplete. The round numbers of the DECIDE messages should be consolidated. Currently, 0 is always output as the decision round (which is the most probable reason for the tests failing).
> Decide phase

- f3/api.go
- f3/granite.go
- f3/participant.go
The public key to use to verify signatures will come from the power table being used as the base for the specific Granite instance. So the verification needs to be done there.
See also #40 for propagating validation results back out to the network layer.
> Move message signature validation into instance, and document the message attestation properties.

- f3/powertable.go
The power table is sorted by power first, not ID, so the duplicate check doesn't work.
> Fix power duplicate entry check

- f3/granite.go
- f3/powertable.go
See #11 
Notice that the removed errors/panics are because (by the execution of the code within the same function) it is impossible for the error/panic to ever occur (either because of the size of slices created or because the error has been checked for previously in the function). 
Also, left panics that reflect a situation of the state of f3 that should never happen (and thus a panic is what suits the code IMO).
> Replace panics where relevant

- test/honest_test.go
Adds a test demonstrating that #64's claim about incorrect behaviour isn't right.
Closes #64.
> Add test demonstrating agreement on longest common prefix

- adversary/absent.go
- adversary/withhold.go
- f3/api.go
- f3/granite.go
- f3/participant.go
- sim/network.go
Alarm handling is idempotent. We no longer need to know which phase an alarm is targetting. Extra alarms, e.g. from a prior instance which since terminated, will not cause any problems.
The code assumes that a participant can have multiple alarms pending. We could probably make this tighter with a "replace alarm" semantic if we think about it, and if it's too difficult to implement multiple alarm.s
> Remove unused payload from alarm callback

- f3/chain.go
- f3/granite.go
- f3/participant.go
- sim/sim.go
- test/honest_test.go
- test/withhold_test.go
The existing code has a subtle bug where some participants could disagree about which epoch a tipset is for, and the correspondence between CID and epoch never checked. We now use the full TipSet object as a map key and for all other uses, and never look at either the CID or Epoch individually. Two nodes are only proposing the same thing if the TipSet fields fully match.
Closes #10
> Use full TipSet object as map key, avoid using CIDs

- f3/granite.go
The existing was a bit wierd.
CBOR-gen already serializes the value as an integer in messages.
> Serialize phase as an integer for signatures.

- adversary/absent.go
- adversary/withhold.go
- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- sim/network.go
@Kubuxu please let me know if this will likely work for your integration.
A complication is that message can only be validated for the currently executing instance. Messages for prior instances can be ignored by this one (but should probably still propagate up to some bound). Messages for future instances can't be validated but must be held and re-delivered when the appropriate Granite instance begins. The Participant used to have a message pool in anticipation of this, but I think that responsibility should be pushed out to the integration instead.
Closes #40.
> Make message validate an exported API of instance and participant, to be called before receiving a message.

- gpbft/gpbft.go
This is highlighting our embarassing lack of unit testing, stemming from origins as just a simulation.
> Fix message validation to check the justification signers have strong quorum

- blssig/signer.go
- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- gpbft/vrf.go
- sim/sim.go
The VRF interfaces were intially created before we had any signing (even fake). The ticket payload creation need not be abstracted, and the signing can be directly invoked on the abstract host Signer.
> Remove abstraction noise around VRF construction and verification

- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- sim/fakesig.go
- sim/sim.go
- test/honest_test.go
- test/withhold_test.go
This is a part of extending to multiple instances #27. Adds a callback API for the GPBFT participant to notify the host of a finality decision. Internally, the instance still terminates by setting appropriate state, and the outer participant checks for termination after each message/alarm. This prevents unintended re-entrancy into the instance.
Following this change through to the simulation framework was surprisingly involved. It now better represents what the real host integration might look like, but still only handles a single instance.
> Add API for participant to notify host of decisions, with signed justification.

- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- sim/sim.go
The API presented by the host to the participant shouldn't require the participant to echo back its ID in method calls. This cleans up most of them. @Kubuxu FYI.
One still remaining is that the `Signer` API requires a node to extracts its own public key from the power table to pass as a parameter. This is convenient for testing Signer, but somewhat awkward for the node (it's a bit of a fluke that it can get its public key this way).
> Remove self participant ID from some host methods.

- gpbft/api.go
- sim/network.go
The protocol only needs one timeout at a time. Supporting many was merely simple in simulation. 
Replacing old alarms will be helpful when implementing multiple instances. I expect it also to be simpler in the production implementation, even if more involved in simulation.
> Change alarm semantics to support at most one at a time

- cmd/f3sim/f3sim.go
- gpbft/api.go
- gpbft/participant.go
- gpbft/powertable.go
- sim/ec.go
- sim/sim.go
- test/absent_test.go
- test/decide_test.go
- test/honest_test.go
- test/withhold_test.go
The participant now immediately starts a new instance after terminating the previous one. The simulator generates chains to provide to these subsequent instances, though for now is limited to supplying all participants with the same chain after the first instance.
~One API change to support this is was adding instance as a parameter when pulling the next chain. It should be possible to do without this, which I might attempt.~
Closes #27, with some follow-up work in #113
> Participant begins new instance after terminating the previous one

- sim/sim.go
- test/multi_instance_test.go
This test fails if the instance count is pushed far above about 1750. I think this is because instances get too far out of sync. This may be resolved by #113.
Note that the immediate instance-based chain visibility is also unrealistic. A better chain model would be timestamp based.
> Add a test exercising multiple instances under ideal conditions

- .github/workflows/ci.yml
- Makefile
- gen/main.go
Use `go:generate` directive to generate sources such that executing `go generate ./...` in root of the project would work.
Set up CI to assert that checked in code is consistent with what `go generate` generates.
Fix typo in CI to trigger builds on the `main` branch.
> Use `go generate` to generate sources

- adversary/absent.go
- adversary/decide.go
- adversary/withhold.go
- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- sim/network.go
- test/honest_test.go
- test/multi_instance_test.go
- test/util.go
This restores a queue of messages for future instances in the participant. Ensuring the delivery of these messages fixed the divergence in multi-instance tests which can now run for significantly longer (no divergence detected yet).
I'm not sure what the network layer should do with messages that can't be validated yet: see #122. Maybe we can close that with this PR, but I'm leaving it open for discussion about the integration problem.
These queues also introduce denial of service risk. See #12.
> Add local queue for messages for future instances

- .github/workflows/ci.yml
As part of `lint` CI workflow, require that `go.mod` is tidy.
> Require `go.mod` is tidy during CI

- cmd/f3sim/f3sim.go
- gpbft/api.go
- gpbft/participant.go
- sim/ec.go
- sim/sim.go
- test/absent_test.go
- test/constants.go
- test/decide_test.go
- test/honest_test.go
- test/multi_instance_test.go
- test/withhold_test.go
Adds the timestamp for next instance as a return value from host's ReceiveDecision callback. This design delegates all knowledge of EC epoch timing and policy about how long to wait for stabilization to the host. Nodes will need to adopt the same policy here to stay in sync but this knowledge doesn't belong inside GBPFT.
Closes #113.
> Delay next instance until EC chain progresses

- gpbft/chain_test.go
- gpbft/types_test.go
Add unit tests that assert expected behaviour from the APIs exported by `gpbft` core types.
Relates to #9
> Implement basic chain and types unit tests

- gpbft/chain.go
- gpbft/chain_test.go
- gpbft/gpbft.go
- gpbft/participant.go
EC chain cannot contain a zero-valued tip set. Enforce this in the exported API and return an error when such tip set is specified in the chain.
Add tests to assert the EC chain invariants are met:
* Epochs in chain are weakly and monotonically increasing, where repeated epochs are not allowed but gaps may exist in the epochs.
* Base cannot be a zero-valued tip set, as defined by `TipSet.IsZero`.
Implement `ECChain.Validate` to encapsulate the chain validation logic, and validate all received chains by a `Participant`. Further, strictly refuse to receive zero-valued chains, since a zero-valued chain is valid but not acceptable by by a `Participant`. The `ECChain` constructor is also refactored to reuse the newly encapsulated validation logic.
Additionally, optimise check for base, prefix, …
> Validate EC chain invariants on instantiation

- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- sim/sim.go
Tracing logic logs is not a fundamental function with gpbft algorithm. Instead, it is a crosscutting concern that currently aids one to reason about the logical changes of a participant.
Refactor the core `Host` interface to relax the requirement for implementing the logic log tracing functionality. Introduce a separate `Tracer` interface that when specified logs logic change logs.
This change separates the tracing requirements introduced primarily by the `sim` package from the core gpbft algorithm interfaces. Additionally, it makes mocking the `gpbft` behaviour for testing purposes simpler.
Note that the tracing concept in simulation defers from the "system logging", in that: it is a configurable textual output of a simulation. Therefore, the work here keeps them separate instead of …
> Refactor `Host` interface to optionally trace logic logs

- .github/workflows/ci.yml
- go.mod
- go.sum
- test/absent_test.go
- test/honest_test.go
- test/multi_instance_test.go
- test/util.go
Speed up tests by ~2X through running simulator test-case repetitions in parallel. The repetition parallelism is by default limited to the number of CPUs. Optionally, it is overridable by setting `F3_TEST_REPETITION_PARALLELISM` environment variable.
Refactor tests to reduce duplicate code and run tests in parallel wherever possible.
Note, the repetition parallelism limit is overridden to 2 for the CI runners. This reduces the test workflow execution time by ~10% compared to default, since the default runners run in a single core.
For comparison, the following lists the test time differences across three configurations:
1) This branch, with default parallelism limit:
```
$ time go test -count=1 ./...
?       github.com/filecoin-project/go-f3       [no test files]
? …
```
> Speed up tests by running repetitions in parallel

- gpbft/participant.go
- gpbft/powertable.go
- gpbft/powertable_test.go
- sim/ec.go
Refine the implementation of power table to utilise the built-in `sort.Interface` for a more concise code.
Change the `Add` receiver to reduce the number of ways by which entry addition can be done. This is to reduce the scope of error across the power table APIs.
Add `Validate` function to power table that asserts its invariants and call it upon receiving a power table instance from the host within gpbft implementation.
Add tests that asserts the validity of a variety of cases, including other power table APIs.
Fixes #146
> Implement sortable power table and test invariants

- cmd/f3sim/f3sim.go
- gen/main.go
- gpbft/chain.go
- gpbft/chain_test.go
- gpbft/gen.go
- gpbft/gpbft.go
- gpbft/types.go
- gpbft/types_test.go
- sim/ec.go
- sim/sim.go
- test/absent_test.go
- test/decide_test.go
- test/honest_test.go
- test/multi_instance_test.go
- test/util.go
- test/withhold_test.go
Removes all internal structure from ECTipset and ECChain, making them entirely opaque. Adds a key type which just stringifies the bytes, ensuring that the entire value is used as a map key. Note that this doesn't yet exactly match the draft FIP (#148).
The internal structure of chain values now needs to be specified elsewhere, but GPBFT will never introspect it.
This also deleted some useful tests for the consistency of chains. When a new type is introduces at the integration layer, those tests should be restored there instead.
Previous PR description below (just introduces the key type) :
<details>
This is a prototype of using the full ECChain payload as a map key, rather than just head tipset ID. It avoids hashing, but just concatenates the bytes and wraps as a string.
This also changes …
> Make ECChain opaque [][]byte in GBPFT

- adversary/decide.go
- adversary/withhold.go
- test/decide_test.go
- test/withhold_test.go
`Decide` and `Withhold` adversaries require an instance of `Host` and access to its power table. Simplify the test setup by retrieving the power table directly from `Host` instead of taking it as an explicit parameter.
> Get PowerTable from Host during adversary testing

- adversary/repeat.go
- test/repeat_test.go
Implement an adversary that echos all messages it receives with a configurable echo count distribution.
Test that  echoed messages do not interfere with consensus even at adversary power of larger than 1/3 of network size.
> Test repeated messages do not interfere with consensus

- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- sim/adversary/absent.go
- sim/adversary/decide.go
- sim/adversary/withhold.go
Update `ChainReceiver` interface to signal whether an EC chain was accepted by an instance or not. This allows tests to assert the current state of a participant and its current GPBFT instance specifically during equivocations testing.
Update `ChainReceiver` godoc to document the pre-existing and new behavior.
> Signal whether an EC chain was accepted by an instance

- sim/config.go
- sim/decision_log.go
- sim/host.go
- sim/latency/latency.go
- sim/message_queue.go
- sim/network.go
- sim/signing/bls.go
- sim/signing/fake.go
- sim/signing/signing.go
- sim/sim.go
- sim/tipgen.go
- test/constants.go
- test/signing_suite_test.go
Break up large go files into separate ones that capture minimal functionality. Encapsulate simulated signing related implementations into their own package, called `signing`.
Rename inconsistent struct/constructor names, and resolve minor lint issues.
Note, the changes here do not make any net functional difference. Instead, they aim to reduce the LOC changed in successive PRs where simulation will be expanded to accommodate more complex scenarios, including more control over adversary message propagation, latency and message loss modeling.
> Refactor `sim` package in prep for expanding the implementation

- .github/workflows/ci.yml
Merge queue is now enabled on `main`. Trigger merge group checks with GitHub Actions.
See:
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
> Trigger merge group checks with GitHub Actions

- sim/adversary/repeat.go
- test/repeat_test.go
Enhance `Repeat` adversary tests by repeating a message based on phase, which stresses convergence beyond max 10 rounds. Add more tests for higher honest count to increase likelihood of equivocations caused by the `Repeat` adversary.
Update documentation for `Repeat` adversary to clarify the semantics of echo.
Address comments raised in #156 post-merge review.
> Enhance `Repeat` adversary tests and add comments

- sim/cmd/f3sim/f3sim.go
- sim/latency/latency.go
- sim/latency/log_normal.go
- sim/latency/zipf.go
- sim/network.go
- sim/sim.go
- test/absent_test.go
- test/decide_test.go
- test/honest_test.go
- test/multi_instance_test.go
- test/repeat_test.go
- test/withhold_test.go
Implement the ability to dynamically change the latency modeling in two ways:
1) per time `t` through a simulation, and
2) between a pair of participants.
This allows simulation of scenarios where re-broadcast is necessary in order to reach consensus.
Additionally, it enables simulation of momentary network partition, and targeted transport attacks by an adversary.
Introduce `Zipf` latency model for a more realistic latency distribution modelling. Follow up PRs will expand tests to make use of this distribution.
> Implement the ability to control latency by time and point to point

- sim/ec.go
- sim/host.go
The simulation has configurations to set the length of an epoch as well as a stabilisation delay before it starts the next instance after one finishes.
Since the original implementation the code has undergone a number of iterations one of which removed epoch from tipset. Since that change, the simulation seem to have been using a fixed next start time upon receiving a decision. The start time is an absolute time; therefore using a fixed time meant that the simulation was not waiting for the configured stabilization in between instances.
Additionally, because the returned start time is used as deliver at timestamp by the simulated network transport alerts may have been fired immediately after a participant received a decision, before all participants finished deciding. This is fine as far …
> Fix a bug in simulated next instance start time

- gpbft/gpbft.go
- gpbft/mock_host_test.go
- gpbft/options.go
- gpbft/participant.go
- gpbft/participant_test.go
- sim/cmd/f3sim/f3sim.go
- sim/options.go
- sim/sim.go
- test/constants_test.go
- test/withhold_test.go
Use `Option` function pattern to implement `gpbft` configuration parameters. Validate the input parameters and use default values if unset. The value of defaults is borrowed from FIP-0086.
Reflect changes in tests and simulation package.
Fixes #184
> Implement `gpbft` option-based configuration with built-in defaults

- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- test/constants_test.go
- test/honest_test.go
- test/util_test.go
Replace collection of acceptable chains received from outside with a collection of candidate chains that is updated to include any that might have been decided by another participant in a previous round.
- Prepare phase now waits to hear from >2/3 of power
- Evidence for CONVERGE is retained in order to justify swaying (and later to propagate to PREPARE)
The sequence of tests in COMMIT is slightly different than the spec, checking first for a strong quorum of COMMIT for bottom, and inferring that if that doesn't exist, any non-bottom COMMIT value could have been decided by another participant.
There is currently a shortcut in CONVERGE, where if the max ticket value cannot be accepted, the participant falls back to their own value instead of iterating through sequential tickets. I think …
> Replace externally-provided acceptable chains with candidate list including possibly-decided values

- test/constants_test.go
- test/multi_instance_test.go
Assert that when latency seed is changed the tests passes eventually. In this case, it looks like the change in latency results in few additional rounds for the test to pass; 21 to be precise.
Increase the max rounds to 30 in order to avoid intermittent errors during dev work that might change latency seeds.
Closes #189
> Investigate sensitivity to latency in multi instance tests

- gpbft/options.go
Update the default delta value to 3 seconds and document the rationale behind it.
The defaults may change in the future once concrete measurements on a live network are performed.
> Set default Delta value to 3 seconds

- sim/adversary/absent.go
- sim/adversary/decide.go
- sim/adversary/repeat.go
- sim/adversary/withhold.go
Since externally-provided acceptable chains are replaced with candidate list the gpbft API no longer requires implementation of `ReceiveECChain` receiver function. Remove it.
> Remove redundant `ReceiveECChain` receiver from adversaries

- gpbft/gpbft.go
- test/util_test.go
> Require justification for PREPARE messages

- Makefile
- test/ballast_test.go
Increase the default `GOGC` by 10x when tests are run using the `make test` target, and respect commandline `GOGC` overrides if set.
Increase the memory ballast to 200MiB for tests.
These changes improve the test runtime by ~50%:
Before:
```
$ time go test ./... -count=1
?       github.com/filecoin-project/go-f3       [no test files]
?       github.com/filecoin-project/go-f3/blssig        [no test files]
?       github.com/filecoin-project/go-f3/gen   [no test files]
?       github.com/filecoin-project/go-f3/sim   [no test files]
?       github.com/filecoin-project/go-f3/sim/adversary [no test files]
?       github.com/filecoin-project/go-f3/sim/cmd/f3sim [no test files]
?       github.com/filecoin-project/go-f3/sim/latency   [no test files]
? …
```
> Reduce GC frequency to run tests faster

- sim/latency/log_normal.go
- sim/latency/zipf.go
When the sender and receiver of a message is the same, always return zero as the latency sample.
Relates to #196
> Adjust latency model to always return zero for local messages

- sim/options.go
- sim/sim.go
Set the default simulation latency to `None` when unset to avoid surprising the user. The default was arbitrarily chosen from the simulation CLI and has no significance.
Change the way max round is calculated, where all participants are checked. Fail if simulation go beyond max.
Relates to #196
> Set default simulation latency to `None`

- gpbft/gpbft.go
> Ignore equivocating and duplicate messages from a sender

- gpbft/gpbft.go
- gpbft/participant_test.go
> Drop messages from prior rounds that can't affect the protocol outcome.

- sim/latency/log_normal.go
- test/constants_test.go
The latency model in simulations is generated using a Log Normal distribution with some configured mean. The latency generation occurs every time a message is sent from any one participant to another participant. This effectively simulates an adhoc network with volatile latency which is typically observed in mobile networks.
Compared to Filecoin network, this approach is unrealistic and too volatile. Because, in Filecoin SPs are typically well-connected servers with high bandwidth low latency connection to their peers. As a result, tests regularly exceed the maximum number of rounds where, so far, they require at least 21 rounds to succeed.
A more realistic latency model is one that uses some randomly generated but fixed point-to-point latency that remains constant or varies very slightly …
> Consistently model P2P latency to reduce max rounds in tests

- sim/message_queue.go
- sim/network.go
- sim/options.go
- test/withhold_test.go
Use `heap.Interface` to simplify the implementation of message passing during simulation by implementing a priority queue. The messages in-flight are priorities in ascending order of their `deliverAt` time, i.e. messages with earlier delivery time have higher priority.
Additionally, explicitly introduce an option to set Global Stabilization Time (GST). GST duration is one of the fundamental assumptions made by gPBFT, beyond which message delivery is assumed to be guaranteed. Enhance Withold adversary tests with varying GST time.
Relates to #196
> Simplify simulation messaging with priority queue and parameterise GST

- gpbft/chain.go
- gpbft/chain_test.go
Truncate the capacity when truncating and extending the chain. That way:
1. Prefixing then extending won't mutate the original chain.
2. Extending the same base chain with one tipset then another won't clobber the first by re-using the capacity from the original slice.
This isn't great for performance, but:
1. `Extend` is only used for testing.
2. Truncating the capacity in `Prefix` has no performance cost unless we decide to append to the chain later.
> Truncate ECChain capacity when extending/truncating

- gpbft/chain.go
- gpbft/participant.go
> Avoid proposing chains that are longer than max.

- .github/workflows/ci.yml
- .gitignore
- Makefile
Change `make test` target to measure code coverage in atomic mode, and extend CI test workflow to upload the reports to Codecov.
> Report code coverage via Continuous Integration

- sim/message_queue.go
- sim/message_queue_test.go
Assert that simulation priority queue used to order message delivery is behaving as expected:
* queued messages are sorted in ascending order of their `deliverAt`.
* removal of a message returns the one with earliest `deliverAt`.
* conditional upsert is respected.
* duplicate messages are allowed and ordered as expected.
* queue is fully drained upon removing all messages.
Update misleading godoc for `Pop` receiver.
Addresses https://github.com/filecoin-project/go-f3/pull/209#discussion_r1600731429
> Add unit tests for simulation message queue

- gpbft/api.go
- gpbft/mock_host_test.go
- gpbft/participant.go
- gpbft/participant_test.go
- sim/adversary/decide.go
- sim/adversary/repeat.go
- sim/adversary/withhold.go
- sim/ec.go
- sim/host.go
- sim/options.go
- sim/sim.go
Step 1 of #151. This is in preparation for fetching power tables for validation of messages for future instances.
See discussion in #151 about the interface design. The powertable offset parameter is encapsulated by the host, which can respond to a request for the power table to use for some (possibly-future) instance. This capability isn't used yet.
This change also removes fixed beacons in the sim, which was previously using the same beacon for every instance. Now it's generated (by setting it equal to the base tipset key bytes).
> Change host API to separate fetching chain from fetching power tables

- gpbft/gpbft.go
- gpbft/options.go
- sim/adversary/spam.go
- sim/sim.go
- test/spam_test.go
The gPBFT rebroadcast design revision introduced an improvement whereby "spammable" messages, i.e. `COMMIT` for bottom, for future rounds should be dropped by the participants. The specification leaves room for implementers to optionally retain some number of such messages to reduce reliance on the need for rebroadcast and ultimately help reach consensus in fewer rounds.
The work here:
1. introduces `WithMaxLookaheadRounds` configuration option to `gpbft` package, defaulting to zero if unset.
2. drops all spammable messages belonging to rounds that are beyond the configured max lookahead rounds.
A `Spam` adversary is introduced to replicate the conditions at which max lookahead rounds would start dropping messages. A set of tests then use the `Spam` adversary to assert that honest …
> Drop spammable messages beyond max allowed lookahead rounds

- .github/workflows/ci.yml
- test/ec_divergence_test.go
Fix lint build failing in merge queue and upgrade to latest linters.
See:
* https://github.com/filecoin-project/go-f3/actions/runs/9190680236/job/25276522745
> Fix go vet issues and upgrade to latest `golangci-lint`

- test/ec_divergence_test.go
- test/honest_test.go
- test/multi_instance_test.go
- test/power_evolution_test.go
UPDATE: until #262 is fixed and we can enable parallelism in `TestHonestMultiInstance_Agreement`, this only saves 3s.
ORIGINAL:
On my modern MBP with `-parallel=8` this gives an improvement of 54s -> 21s.
A little more is possible, but see #262.
> Add more parallelism to tests in t.Run()

- test/multi_instance_test.go
`FuzzHonestMultiInstance_AsyncAgreement` intermittently fails on CI, most likely due to taking too long to complete a test.
To avoid intermittent failures:
* change the honest multi instance tests to cover incremental network sizes, up to 4
* reduce the length of randomly generated EC chains at each instance as this should not affect the test quality for what it is testing. But it should make it run faster due to less GC.
Additionally, add static corpus that failed locally after extended fuzz time to the fuzz test.
Fixes #251
> Adjust Fuzz honest multi-instance to avoid intermittent failures

- gpbft/gpbft.go
- sim/adversary/deny.go
- sim/options.go
- sim/sim.go
- test/skip_to_rounds_test.go
Implement a rebroadcast protocol improvement where upon receiving sufficient justification a participant jumps ahead to future rounds. Justification from a future rounds is considered sufficient when the participant receives:
* at least one `CONVERGE` message, and
* a weak quorum of `PREPARE` messages
for that round.
The changes here introduce a test that should trigger skipping to future rounds once reboradcast is implemented. The test uses a `Deny` adversary where all messages to and from a set of targets are dropped until GST has elapsed. For now, however, the test is skipped.
Fixes #241
> Skip ahead to future rounds when justified

- Makefile
- test/absent_test.go
- test/decide_test.go
- test/honest_test.go
- test/multi_instance_test.go
- test/power_evolution_test.go
- test/repeat_test.go
Reduce GC by reducing the size of EC chain generated by the fuzz tests. The size of EC chain makes no difference to the coverage.
In one case reduce the honest count from 5 to 4 in order to avoid intermittent failures due to fuzz tests taking too long.
> Reduce GC during fuzz tests

- gpbft/gpbft.go
Update the core protocol implementation to allow skipping to future rounds from QUALITY phase. This reduces the conditions to requiring an instance to only fully execute DECIDE phase. Otherwise, the instance may jump ahead as long as all queued messages are processed.
As a result, the implementation no longer needs to check for QUALITY phase transition on receiving alarms.
Fixes #278
> Allow skipping to future rounds from QUALITY phase

- gen/main.go
- gpbft/api.go
- gpbft/chain.go
- gpbft/gen.go
- gpbft/gpbft.go
- gpbft/mock_host_test.go
- gpbft/participant.go
- gpbft/participant_test.go
- gpbft/signature_test.go
- host.go
- sim/host.go
- sim/signing/fake.go
In addition to committing to a power table in each tipset, agree on:
1. The next power table (used to validate the next instance).
2. Arbitrary commitments (will be used by F3 for snark-friendly power tables, and other fields).
fixes #257
> Commit to a next power table and additional commitments

- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- gpbft/participant_test.go
I'm interested in any suggestions of how to test this. I looked into the existing participant tests, but it seemed unlikely the mock is safe to use concurrently and difficult to test this without that. We could manually construct a harness. Is that worthwhile?
See #151
> Make message validation safe for concurrent use.

- gpbft/api.go
- gpbft/gpbft.go
- gpbft/participant.go
- gpbft/participant_test.go
> When starting a new instance, check for skipping rounds just once after processing all queued messages.

- gpbft/gpbft.go
> Avoid loading round state for dropped messages

- .github/workflows/ci.yml
- sim/signing/bls.go
- sim/signing/fake.go
Fix a race condition in simulation signing package key generation.
Run tests with race detection enabled in a separate CI job to avoid
slowing down the regular tests as they take significantly longer to
finish.
Fixes #288
> Fix race conditions and Run tests with race detection in CI

- blssig/signer.go
Replace the deprecated `kyber/sign/bls` with the new `kyber/sign/bdn`. Even though the implementation uses the deprecated package for signing only and is safe to rogue key verification there seem to be no reason not to use the newer package.
> Fix deprecated package in bls signer

- certstore/certstore.go
- sim/signing/fake.go
Fix minor staticcheck issues to reduce noise in local development environment. These issues don't seem to have been picked up by golangci-lint.
> Fix minor staticcheck issues

- gpbft/gpbft.go
Previous iterations of FIP-0086 made use of weak quorum in chain state, but the latest changes no longer require it. The only place that the notion of weak quorum is used is in skipping to future rounds, where it is only needed at quorum state. Hence the unused code removal at chain support.
Fixes #233
> Remove redundant weak quorum flag from chain support

- gpbft/gpbft.go
When quorum state dictates that a strong qorum is present, then there must be a corresponding `QuorumResult`. If it is not found, then it is an indication of corrupt internal state most-likey caused by a bug. In which case, error fatally.
Fixes #234
> Error out fatally when strong quorum exists but not found

- cmd/f3/run.go
- f3.go
- gpbft/participant.go
- host.go
It simplifies the structure of F3, gpbftHost/Runner. gpbftHost becomes a newtype of gpbftRunner to isolate exposure of APIs.
> Rename Module to F3, pass network name to Client, fix error wrapping

- gpbft/chain.go
- gpbft/chain_test.go
- gpbft/gen.go
- gpbft/gpbft.go
- gpbft/participant_test.go
- sim/options.go
- test/util_test.go
> Enforce size limits on TipSet key and power table CID length.

- sim/host.go
- sim/network.go
- sim/sim.go
Logs were being plumbed directly to the network rather than the per-participant wrapper.
> Fix plumbing of per-participant logger.

- gpbft/gpbft.go
When sufficient justification is received do not wait for timeouts to expire in PREPARE phase.
Part of #242
> Shortcut timeout in PREPARE when outcome is determined

- test/honest_test.go
Avoid modifying test case options during parallel test execution.
> Fix race condition in honest tests

- gpbft/api.go
- sim/message_queue.go
- sim/message_queue_test.go
- sim/network.go
Document the implicit assumption that the delivery of alarms to a participant must take precedence over broadcast messages.
Adjust simulation message queue to respect the alarm ordering.
Fixes #316
> Document and adjust alarm delivery precedence over network messages

- certstore/certstore.go
- certstore/certstore_test.go
- f3.go
This commit adds power tables to the certificate store.
1. It stores a full power table every `60*24` instances (twice a day on Filecoin).
2. From there, it applies deltas from finality certificates to recover any requested power table.
> Add power tables to the Certificate Store

- gpbft/participant.go
- sim/sim.go
- test/deny_test.go
The `SkipToInstance` API is intended to be called by an honest integrator whenever a finality certificate is observed from a future instance.
As a result `TestDeny_SkipsToFuture`, previously skipped, can now be run when the simulation itself (playing the role of honest integrator) notifies participants of the existence of a future round whenever it is applicable.
The changes here introduce a new participant receiver to get the current instance, and notified of future instance when it is behind the latest completed one.
> Simulate skip to future instances for lagging participants

- gpbft/api.go
- gpbft/errors.go
- gpbft/errors_test.go
- gpbft/gpbft.go
The validation errors are numerous enough to grant the presence of some higher level grouping for convenient API usage. This allows the users to infer whether an error was caused by validation without having to list every sentinel error associated with validation errors.
Relates to: https://github.com/filecoin-project/go-f3/pull/294#discussion_r1626602926
> Group validation errors as top level `ValidationError`

- gpbft/api.go
- gpbft/participant.go
I included the exported methods that are not part of an interface, since the sim really shouldn't be invoking these concurrently either.
Closes #304.
> Protect exported participant methods with tryLock

- f3.go
- host.go
Correct the spelling of `Client.IncomingMessages` receiver.
> Fix typo in interface method name

- gpbft/gpbft.go
- sim/adversary/decide.go
- sim/adversary/repeat.go
- sim/adversary/spam.go
- sim/adversary/withhold.go
- sim/ec.go
- sim/host.go
The supplemental data provided by host is required for additional validation. It is already present in the payload of message builder but not the final `GMessaage`s built from it.
The changes here broadcast supplemental data as part of `GMessage` and enhances simulation to generate a unique supplemental data per instance that is required to be consistent across participant for a given instance.
Fixes #335
> Broadcast supplemental data as part of `GMessage`

- cmd/f3/run.go
- f3.go
- gpbft/api.go
- gpbft/options.go
- gpbft/participant.go
- gpbft/participant_test.go
- host.go
- sim/adversary/absent.go
- sim/adversary/decide.go
- sim/adversary/deny.go
- sim/adversary/repeat.go
- sim/adversary/spam.go
- sim/adversary/withhold.go
- sim/sim.go
Removes the initialInstance config option too, in favour of the runtime parameter.
The parameter is necessary for in every case except the initial instance, i.e. it's not a one-time static value like other options. Given the single entry point, if we left the config option there as well, there would be two different initial instances at bootstrap, which would be confusing. This parameter makes the data flow of the initial instance very clear, providing it exactly when it is first needed.
> Merge participant Start and SkipToInstance into a single StartInstance method.

- gpbft/api.go
- gpbft/gpbft.go
- sim/latency/log_normal.go
- sim/latency/zipf.go
- sim/message_queue.go
- sim/message_queue_test.go
- test/deny_test.go
The gpbft implementation implicitly assumes that broadcast of `CONVERGE` messages to self are delivered immediately. In practice this assumption does not hold because of the complexity in deferred signing and async message delivery.
The changes here relax this assumption by explicitly notifying the local converge state that the self participant has begun the `CONVERGE` step, providing self proposal and justification for the proposal. The code then considers the given data whenever search in converge state does not bear any results, caused by asynchronous message delivery. Further, the code ignores the self converge value once at least one broadcast message is received.
Additionally, the changes remove zero-latency for messages to self in simulations to make a stronger assertion that …
> Relax the assumption of receiving own `CONVERGE` messages synchronously

- certs/certs.go
- certs/certs_test.go
- f3.go
- gpbft/gpbft.go
- gpbft/message_builder.go
- gpbft/powertable.go
- gpbft/powertable_test.go
- sim/adversary/decide.go
- sim/adversary/repeat.go
- sim/adversary/spam.go
- sim/adversary/withhold.go
- test/util_test.go
When we construct a power table, we now:
1. Scale individual power into the range 0-0xffff.
2. Treat the sum of these _scaled_ powers as the maximum power from the perspective of "quorum". We can't use 0xffff as the "total power" due to compounded rounding errors.
Then, we use this scaled power when determining if we have quorum. However, we _don't_ use it for either:
1. Tickets weight.
2. Determining if an SP is eligible to be included in the power table itself.
fixes #33
> Scale power in the range 0-0xffff

- gpbft/gpbft.go
When justified by a strong quorum, shorten the timeout at `COMMIT` phase.
Fixes #242
> Shorten timeout at `COMMIT` phase when justified

- sim/adversary/adversary.go
- sim/adversary/decide.go
- sim/adversary/spam.go
- sim/adversary/withhold.go
- sim/host.go
- sim/network.go
To implement some adversary models the simulation package introduces an interface that allows an adversary host to immediately propagate a message across the network.
Since the original implementation the core broadcast mechanisms has evolved into async `RequestBroadcast` that takes a builder. But the pattern is not fully applied to the simulation specific flavour of synchronous broadcast.
The changes here use the same builder pattern in simulation and reflect changes across adversary models.
> Use consistent request broadcast pattern in simulated sync broadcasts

- gpbft/gpbft.go
- gpbft/options.go
- sim/adversary/deny.go
- sim/adversary/drop.go
- sim/adversary/repeat.go
- sim/sim.go
- test/absent_test.go
- test/constants_test.go
- test/deny_test.go
- test/drop_test.go
- test/power_evolution_test.go
- test/repeat_test.go
- test/spam_test.go
When the current instance has not progressed after some time rebroadcast the last round of messages. The rebroadcast time is made configurable using a bounded exponential backoff after phase timeout expires.The rebroadcast timeout is offset by phase timeout when not expired, and by latest rebroadcast time after that.
Once the first rebroadcast is triggered successive rebroadcasts use the `Clock` alarm mechanism to daisy-chain the triggers one after another.
Introduce `Drop` adversary to simulate scenarios where for a given set of target participants messages are dropped based on some configured message loss probability. Simulate tests using the `Drop` adversary and assert that despite stochastic message loss the targeted participant reaches the expected consensus.
Fixes #243
> Rebroadcast last round of messages if instance has not progressed

- gpbft/gpbft.go
The alarming system is used to schedule successive rebroadcasts should the conditions permit rebroadcasting messages. The alarming system works using absolute time. This means if a node is busy with other things, e.g. processing queued messages, an alarm might not fire at absolute specified time.
Apart from the initial rebroadcast all other successive rebroadcast alarms are offset based on the previous rebroadcast timeout. This means if the triggering of an alarm is delayed for whatever reason the absolute rate at which rebroadcast happens remains constant. This can result in unnecessary message rebroadcast and eventual saturation of message queue by repeated rebroadcasts.
The changes here avoid this issue by using the current host time to schedule the next rebroadcast after one …
> Always offset the successive broadcasts based on current time

- gpbft/chain.go
Fix bug where tipset stringer would panic if its length is less than 16 bytes.
Refine `ECChain` stringer to skip building the string value if max length is reached, instead of fully build then truncate.
> Fix tipset stringer max print limit and refine ec chain stringer

- gpbft/gpbft.go
This aligns more directly with the FIP pseudocode. The conditions are logically equivalent given assumptions that there can only be one possible non-zero value after the PREPARE phase.
Part of #244.
> Use CouldReachStrongQuorumFor value when checking if CONVERGE value should become a candidate.

- cmd/f3/manifest.go
- cmd/f3/run.go
- f3.go
- go.mod
- gpbft/participant.go
- host.go
- manifest/manifest.go
- manifest/static.go
- passive/dynamic_manifest.go
- passive/manifest_sender.go
- test/f3_test.go
Depends on https://github.com/filecoin-project/go-f3/pull/348
This PR:
Implements all the logic to handle the reception of new manifests, and to trigger a rebootstrap when the change is received. The implementation of configuration changes without rebootstraps (mainly EC config and power table changes), will come in the next PR.
Implements a simple manifest sender that periodically broadcast the current manifest used by the network.
Includes a really simple testing harness for F3 over real libp2p hosts to test all the pubsub integration and the distribution of manifests.
Implementation of the logic when a manifest change doesn't trigger a rebootstrap and power table updates.
> F3-229: dynamic manifest handler, manifest sender, f3 integration tests

- gpbft/gpbft.go
- gpbft/message_builder.go
- gpbft/powertable.go
- gpbft/powertable_test.go
- sim/adversary/decide.go
This brings us in-line with the FIP.
> feat: use the scaled power for winning tickets

- host.go
- manifest.go
ECDelay is how long we wait before finalizing a tipset, but it isn't necessarily the time between instances (it's actually 2x right now in lotus). ECPeriod is the time between instances.
The new logic waits `ECDelay + ECPeriod * multiplier` where I've reduced each multiplier by 1 to account for the added delay.
Additionally:
1. We now use `now+ECPeriod` when we fail to get the tipset from lotus.
2. ECDelay defaults to 60s (same as lotus).
NOTE: I'm not sure if this new logic is correct, but the old logic definitely had some issues so I'm opening this PR for discussion.
> Correctly use ECPeriod & ECDelay

- emulator/driver.go
- emulator/driver_assertions.go
- emulator/host.go
- emulator/instance.go
- emulator/signing.go
- gpbft/gpbft_test.go
Implement an emulator to test the core GPBFT protocol, with fine-grained control and assertion over message-by-message progress of a participant.
Add utility functions to reduce the boilerplate code during testing and implement state transition tests that assert state transition occurs:
* for proposal when there is strong evidence of prepare.
* for base when there is no strong support for any proposal
* for base by timeout alone for a sole participant.
Part of #9
> Implement a GPBFT emulator and test state transitions

- emulator/driver.go
- emulator/driver_assertions.go
- emulator/host.go
- emulator/instance.go
- gpbft/gpbft_test.go
Add two new tests that assert:
* messages arriving before instance is started are processed.
* messages arriving after instance is started that belong to future rounds are processed.
Part of #9
> Test GPBFT queues and drains future instance messages

- cmd/f3/manifest.go
- manifest/manifest_sender.go
Implement a libp2p server that serves dynamically changing manifests by periodically checking a given manifest path for change. Once change is detected it then uses the manifest sender to publish the new manifest version on pubsub.
Integrate the manifest server into `f3` CLI via command `f3 manifest serve`.
> Implement dynamic manifest libp2p server

- host.go
- manifest/manifest.go
- manifest/manifest_test.go
- test/f3_test.go
Additionally move backoff params to manifest
> Revert changes to EC backoff introduced in #382

- test/f3_test.go
Race tests will sometimes fail here, there exists ordering of goroutine
execution where ctx.Done() fires first within Runner and propagates through the errCh and select picks it over the context.
> Maybe fix spurious error in tests

- f3.go
Defer can only override named return values.
> Fix error return in F3.Run

- .github/workflows/publish-ghcr.yml
Include both linux arm64 and amd64 platforms when building and publishing container.
Update push action to latest.
Part of #396
> Publish container images for both arm and amd 64

- cmd/f3/manifest.go
Avoid failing fatally if connection to bootstrap servers fails. It is possible that some or all the bootstrap server addresses are down, in which case proceed with running the manifest server and simply output the connection failure.
> Fail gracefully on manifest server bootstrap connection

- certexchange/polling/poller.go
Use explicit version for `stringer` generator to assure consistent output from `go generate ./...`.
> Explicitly set the `stringer` version in go-generate

- emulator/driver.go
- emulator/driver_assertions.go
- gpbft/gpbft.go
- gpbft/gpbft_test.go
- sim/adversary/repeat.go
Fix a bug where rebroadcast parameters are never reset within a round, because of the way by which "progress" was determined: The previous implementation stored last seen round/phase on broadcast and compared it to the current round to infer whether progress has been made. This approach would always result in no progress since on phase/round change
the broadcast state would update the references based on the last broadcast. Therefore the current round/phase always matched the last seen round/phase in broadcast state.
The changes here resolve the issue by explicitly resetting the rebroadcast params upon progress by explicitly resetting rebroadcast params on phase change. Based on a few retries this makes up the most readable code IMHO.
The changes also add a test that assert the right set …
> Test rebroadcast and fix rebroadcast reset issue

- emulator/driver_assertions.go
- gpbft/gpbft.go
- gpbft/gpbft_test.go
Test that instance does not skip to round unless it not in decide phase, it has seen at least weak quorum of prepare and finds a max ticket.
Part of #9
> Test skip to round

- gpbft/gen.go
- gpbft/gpbft.go
96 is the size of the compressed representation of BLS-381 G2 point, which is the scheme we use for signatures. It is the larger of two possibilities, with signatures on G1 being 48 bytes.
> Limit size of signatures to 96 bytes

- gpbft/gpbft.go
To ensure no arithmetic properties leak from BLS-G2 affine compressed
representation.
> Hash ticket before performing arithmetic

- certexchange/client.go
- certexchange/polling/common.go
- certexchange/polling/common_test.go
- certexchange/polling/poller_test.go
- certexchange/polling/subscriber.go
- certexchange/polling/subscriber_test.go
- certexchange/protocol_test.go
- certexchange/server.go
- cmd/f3/run.go
- f3.go
- host.go
- logging.go
- test/f3_test.go
It was causing circular import issues (which could have been fixed by moving it, I guess) but, more importantly, the abstraction really wasn't pulling its weight. We're keeping it out of GPBFT itself but our other packages already depend on things like go-datastore and go-libp2p, so depending on go-log doesn't really matter.
> Import go-log directly (except in GPBFT) and remove Logging

- cmd/f3/run.go
- f3.go
- gpbft/message_builder.go
- gpbft/message_builder_test.go
- host.go
- test/f3_test.go
We use this internally for simulation testing where performance is
critical. The user should never change this.
> Don't make the SigningMarshaler customizable in F3

- certexchange/client.go
- certexchange/server.go
1. We set the deadline on the context as well, so the stream deadline isn't actually critical.
2. The mock libp2p implementation doesn't support them.
> Ignore errors when failing to set stream deadlines

- host.go
Also skip passed multiple certificates.
> Fix instance skipping inequality check

- gpbft/gpbft.go
- gpbft/payload_test.go
Fix a bug in payload equality check where comparison with nil payload would result in panic.
Add equality and signing serialisation tests.
> Fix bug in payload equality check and payload unit tests

- emulator/driver.go
- emulator/host.go
- emulator/instance.go
- gpbft/gpbft.go
- gpbft/message_builder.go
- gpbft/message_builder_test.go
- gpbft/participant_test.go
- host.go
- sim/adversary/decide.go
- sim/adversary/repeat.go
- sim/adversary/spam.go
- sim/adversary/withhold.go
- sim/network.go
And, importantly, avoid mutating it after creating it. Especially given that we now store/rebroadcast these message builders, I'll feel a lot more comfortable if they're immutable.
> Remove MessageBuilder locks

- cmd/f3/run.go
- f3.go
- host.go
- test/f3_test.go
Otherwise rebroadcast will end up dropping the last and most important messages when the message bus blocks.
fixes #443
> Broadcast messages via a blocking channel

- gpbft/participant.go
- gpbft/participant_test.go
Due to async message delivery, we'll frequently get messages from the wrong instance. Log (trace) and drop them.
Part of #421.
> Skip messages from the wrong instance instead of returning an error

- version.json
Note that the latest pushed tag is 0.0.2, hence the bum to 0.0.3.
> Bump version file to 0.0.3 in prep for release

- codecov.yml
1. Ignore generated cbor-gen files.
2. Ignore the command itselt (not going to be covered by unit tests).
> ci: fix coverage ignore

- certstore/certstore_test.go
- merkle/merkle_test.go
- test/f3_test.go
- test/signing_suite_test.go
- test/withhold_test.go
The main slowdown is due to the main "F3" tests, but we might as well run tests in parallel wherever possible. I excluded the certificate exchange tests as parallelizing them actually slowed everything down a bit.
> Improve test parallelism

- ec/fake_ec.go
- gpbft/chain.go
- gpbft/gpbft.go
- gpbft/participant.go
- gpbft/participant_test.go
- gpbft/payload_test.go
- gpbft/signature_test.go
- gpbft/vrf.go
- host.go
- sim/signing/fake.go
The codebase inconsistently follows the MaxCaps golang naming convention for constant.
Consistently use MaxCaps for all constants, except for PHASEs to keep the code easier to read.
> Follow golang naming convention for constants

- host.go
- manifest/manifest.go
- manifest/manifest_test.go
- test/f3_test.go
Fix minor typo in spelling of "committee".
> Fix typo in manifest EC config

- ec/powerdelta.go
- ec/powerdelta_test.go
- f3.go
- manifest/manifest.go
- manifest/manifest_test.go
- test/f3_test.go
This switches from deltas to:
1. Explicit power entries that extend/replace power entries in the EC power table.
2. A flag that ignores the EC power table entirely.
That way, we can test this out with a limited set of SPs and/or disable problematic SPs.
Fixes #463
> Make it possible to disable some/all participants via the manifest

- cmd/f3/manifest.go
- cmd/f3/run.go
- gpbft/powertable.go
- gpbft/powertable_test.go
- manifest/dynamic_manifest.go
- manifest/dynamic_manifest_test.go
- manifest/manifest.go
- manifest/manifest_sender.go
- manifest/manifest_test.go
- test/f3_test.go
This also allows us to re-config without re-bootstrap (by restarting the local F3 instance). This is only safe for non-consensus parameters and will be horribly unsafe until we fix 392.
Also:
- Removes reliance on hashing json, relies on the network name and manual equality checks.
- Removes versions. We now expect the version to be explicitly specified in the network name.
- Starts message sequence numbers at the current time so we don't need to save them.
- Remove the EC from the dynamic manifest provider as it's unused.
- Tests.
fixes #468
> Remove manifest versions

- manifest/manifest.go
Set the default cert exchange configuration in the local devnet manifest, since nil cert exchange config causes panic.
Relates to: https://github.com/filecoin-project/lotus/pull/12236
> Set default Certificate exchange config in local devnet manifest

- .github/workflows/releaser.yml
- version.json
Bump the version in prep for release of `v0.0.4`.
Use default GA secret to allow CI to make the tag until UCI specific secret is created.
> Bump version in prep for releasing `v0.0.4`

- test/f3_test.go
Hopefully this will deflake it a bit. It usually works, just not when running with the race detector (in parallel).
> Test: Wait a bit longer in TestF3PauseResumeCatchup

- certs/cbor_gen.go
- certs/certs.go
- certs/certs_test.go
- certstore/certstore.go
- certstore/certstore_test.go
- f3.go
- gen/main.go
- go.mod
- internal/powerstore/powerstore.go
- internal/powerstore/powerstore_test.go
If we fall more than 1.5 EC finality behind, this will start storing power deltas up to EC finality (checking every 1/4 EC finalities).
NOTE: this records power deltas by-epoch. That should be safe enough for now but I'd like to switch to tipset keys before mainnet launch in case.
I implemented this as a completely separate service so the runner doesn't need to know that state can be garbage collected (and so we can keep it running even if we pause GPBFT). Although... we might not want to?
fixes #479
> Implement the "ohshitstore"

- emulator/instance.go
We share them between threads/nodes.
> Emulator: Clone the power entries before modifying

- certstore/certstore.go
- internal/powerstore/powerstore.go
- internal/powerstore/powerstore_test.go
- test/f3_test.go
The certstore stores the _base_ power table, not "future" power tables. So we need to keep EC power tables around until we've passed the instance lookback.
Also, fix an issue in the certstore where we were storing power tables one epoch after we should have.
> Engague the OhShitStore based on the f3Base, not the head

- .github/workflows/releaser.yml
It seems later version of unified CI have fixed the missing input to releaser Github actions workflow. The reason custom releaser secret exists is to allow release to trigger other work flows _if_ the custom secret is set.
F3 does not have that need, and the default behaviour falls back on the built-in github secrets token. Hence, the removal of custom secret config altogether.
See:
- https://github.com/ipdxco/unified-github-workflows/commit/6e469c704d60a96626da7d2131ae46859d311a67
Fixes #449
> Remove releaser custom secret from CI

- test/f3_test.go
Nodes can be at different instances and we were racing against the wrong node (0 v 2).
fixes #461
> test: fix TestPauseResumeCatchup flake

- certstore/certstore_test.go
No matter when we look. Previously, we had a "dead" instance immediately after we should have stored the power table (fixed in #490).
> test: verify that we can get the power table for an instance

- cmd/f3/manifest.go
- manifest/manifest.go
- manifest/manifest_test.go
Move manifest unmarshalling to a package level function that can correctly unmarshal "null" JSON string as `nil` manifest pointer.
Add tests that assert expected behaviour.
> Implement nil manifest unmarshalling

- manifest/dynamic_manifest.go
- manifest/dynamic_manifest_test.go
- manifest/manifest.go
- manifest/manifest_sender.go
- test/f3_test.go
related to https://github.com/filecoin-project/go-f3/issues/502
> Remove explicit pause/resume from the manifest sender

- gpbft/metrics.go
- metrics.go
To avoid reporter specific behaviour manually prefix all metrics with f3 (and package when appropriate).
> Prefix all metric names with f3

- certexchange/client.go
- certexchange/polling/poller.go
Because the request is async and we may abort for some reason (e.g., invalid certs), make sure to actually cancel the underlying request before returning.
Also return early without spawning a goroutine if we're only asking for a single power table.
> certexchange: cancel request context when returning

- version.json
Make a new tagged release in prep for lotus dependency bubble-up.
> Release `v0.0.5`

- gpbft/options.go
- gpbft/options_test.go
- manifest/manifest.go
- version.json
At back-off number 84 (~42minuntes with no progress), the backoffer would return negative duration.
> Fix exponentialBackoffer overflowing into negative, bump protocol version

- cmd/f3/run.go
- ec/fake_ec.go
- ec/powerdelta_test.go
- f3_test.go
- internal/powerstore/powerstore_test.go
We now have mock time support, so we can just use that. As a matter of fact, none of our code actually _used_ EC without time (well, we had a few tests that constructed it without time but they never advanced head).
> Remove time-less FakeEC

- f3.go
- host.go
- metrics.go
Measure the time spent on validating messages and tag the metric by validation result.
> Measure time spent on validating messages tagged by result

- certexchange/client.go
- certexchange/metrics.go
- certexchange/polling/metrics.go
- certexchange/polling/peerTracker.go
- certexchange/polling/peerTracker_test.go
- certexchange/polling/subscriber.go
- certexchange/server.go
- certexchange/util.go
- internal/mhelper/mhelper.go
This adds basic metrics so we can know how many requests we're making, how many peers we're talking to, how often we're polling, etc.
I still want to add some metrics around how often we're polling when we don't _need_ to, but I also want to rework some of that logic at the same time to reduce the number of unnecessary polls. So I'm punting that out of this round of work.
> Add basic certificate exchange metrics

- gpbft/metrics.go
- metrics.go
For better accuracy and compliance with otel best practices measure the time spent on validating messages as float64 seconds.
While at it, use inline var struct instantiation instead of init to follow a consistent convention across the repo.
> Measure time spent on validation as seconds in float64

- certexchange/client.go
- certexchange/polling/subscriber.go
- certexchange/server.go
Thanks to @kubuxu TIL this function exists. Use it instead of manually calculating elapsed time in seconds with float64 accuracy.
> Use built-in time.Seconds to measure elapsed time as float64

- host.go
- metrics.go
- metrics_test.go
As part of understanding duplicated effort and eventually designing a caching mechanism to reduce it, measure the number validations that are performed for messages, and separately for justifications.
The most expensive part of validation is signature validation, two of which exists at `GMessage` and `Justification`. Measuring the duplicate validations at the top level should help us understand the gain in caching already validated signatures.
The implementation introduces a new data structure to determine whether a given message/justification is seen before or not, identified by signatures. The implementation uses a total bounded size of 50K entries divided equally across counting duplicate messages and duplicate justifications. This number should be large enough to provide a reasonable …
> Measure duplicate validated messages within a bounded size

- Dockerfile
- Fix AS case.
- Add a newline.
> Make docker happy

- f3.go
chore: Fix typo in `waiting for` log
> chore: Fix typo in `waiting for` log

- manifest/manifest_sender.go
- manifest/metrics.go
Add metrics that report the latest manigest being used by the sender along with additional metrics about the sender itself. This should make it easier to overlap changes relative to manifest update.
Fixes #539
> Add manifest sender metrics

- blssig/aggregation.go
- blssig/metrics.go
- blssig/verifier.go
- internal/measurements/attributes.go
I threw in the panic handlers just to be complete, I've seen too many panics in cryptography code.
> Add signature verification/aggregation metrics and panic handlers

- host.go
- metrics.go
Measure the total number of duplicate messages, along with duplicates, justified, and duplicate justifications.
This should provide a finer grain data for a more educated cache design.
> Measure the number of validated messages with a finer grain tagging

- Makefile
Remove the GOGC override for CI fuzz tests, because:
* without it fuzz tests run faster,
* we are close to the runner's memory limit, and we get false positive failures caused bo GitHub Actions SIGTERM if we go over the limit.
> Restore default GOGC for CI fuzz tests

- Makefile
- certexchange/client.go
Although the CI uses staticcheck only, the team's preference is to continue and use golangci in `make lint`.
Fix the version of golangci-lint used for a more consistent checking, and fix the golangci lint issues not picked up by CI.
> Use a fixed version of golangci-lint and fix lint issues

- gpbft/gpbft.go
- logging.go
1. Update round after logging so we log with the correct round.
2. Fix the logger skip.
> Improve GPBFT Logging

- f3_test.go
- host.go
- manifest/manifest.go
- manifest/manifest_test.go
When catching up, we expect many single-round instances consisting of 4 phases. So we try to align our start times with that to avoid staggering.
This should probably have a simulation test...
fixes #550
> Align catch-up GPBFT start times with the expected instance interval

- manifest/manifest.go
- manifest/manifest_test.go
This adds rebroadcast backoff config to the manifest. Unfortunately, this will require a network protocol bump if we actually want to change this.
> Add GPBFT backoff to manifest

- gpbft/gpbft.go
Add logging to indicate when rebroadcast timeout is set and when rebroadcast is successful along with the number of messages rebroadcasted.
> Improve logging around rebroadcast

- cmd/f3/manifest.go
- cmd/f3/observer.go
- cmd/f3/pusub.go
- f3_test.go
- host.go
- internal/psutil/psutil.go
- manifest/dynamic_manifest_provider.go
- manifest/dynamic_manifest_sender.go
- manifest/manifest.go
- manifest/manifest_test.go
1. Add topic scoring to both the GPBFT topic and the manifest topic.
2. Use hashing for message IDs in the manifest network and increase the rebroadcast time.
3. In the manifest validator, drop messages with old sequence numbers.
> Add topic scoring & reduce pubsub spam

- certstore/metrics.go
Unfortunately, otel only works well with timeseries data and we don't have that here. So I'm switching back to a gauge because that's the best we can do.
> Go back to using a gauge for instance sizes

- certs/certs.go
- certs/certs_test.go
- gpbft/gpbft.go
- gpbft/message_builder.go
- gpbft/participant.go
- gpbft/powertable.go
- gpbft/ticket_quality.go
- sim/justification.go
Because we're double-counting adversary power here, we could overflow. We fix this by:
1. Switching from uint16 int64 (which simplifies our code anyways).
2. Limiting the possible support to the total power.
> Fix power overflow issues when checking for a potential strong quorum

- gpbft/ticket_quality_test.go
Depending on the CPU architecture, the ticket quality tests fail due to differences in exact fraction calculation.
Update the tests to:
* always assert delta of 1e-15 for fraction
* assert epsilon error of 1e-3 when fraction is non-zero (otherwise relative error can't be calculated)
* assert exact equality when fraction is zero.
This is an slight overkill in assertion for the benefit of documenting intent in an executable test.
> Adjust epsilon for ticket quality tests

- Makefile
- certs/cbor_gen.go
- certs/certs.go
- gpbft/cbor_gen.go
- gpbft/powertable.go
The maximum size of public key is 48 bytes. Enforce it in cbor-gen as struct tags.
Fixes #547
> Enforce maximum public key size to 48 bytes

- internal/caching/set.go
Clearing seems to be very slow, it's making
`FuzzHonestMultiInstance_SyncAgreement` take 2x longer. This is probably
because the keys are large and by-value? I'm not sure, but the cost of
re-allocating these maps shouldn't be huge anyways...
> Replace cache set maps instead of clearing them

- gpbft/gpbft.go
Move the handling of late-arriving COMMITs into switch statement for consistent code style and better readability.
> Refactor handling of late-arriving COMMITs

- gpbft/errors_test.go
- gpbft/gpbft_test.go
- gpbft/participant_test.go
- gpbft/payload_test.go
- gpbft/powertable_test.go
- manifest/manifest_test.go
- merkle/merkle_test.go
- sim/message_queue_test.go
- test/deny_test.go
- test/drop_test.go
- test/ec_divergence_test.go
- test/honest_test.go
- test/multi_instance_test.go
- test/repeat_test.go
- test/spam_test.go
- test/withhold_test.go
Now that we are using Go 1.22 remove redundant re-declarations of for loop variables.
> Remove redundant loop variable redeclaration in light of Go 1.22

- certexchange/client.go
- certexchange/protocol_test.go
- certs/certs.go
- certstore/certstore.go
- certstore/certstore_test.go
- ec/fake_ec.go
- emulator/instance.go
- go.mod
- gpbft/cbor_gen.go
- gpbft/chain.go
- gpbft/chain_test.go
- gpbft/gpbft.go
- gpbft/gpbft_test.go
- gpbft/participant_test.go
- gpbft/payload_test.go
- gpbft/powertable.go
- gpbft/signature_test.go
- sim/ec.go
- sim/options.go
- sim/signing/fake.go
- test/decide_test.go
- test/util_test.go
1. Encode CIDs with the correct CBOR tags.
2. Use the upstream go-cid library.
We were already depending on the CBOR library and, at a minimum, I want to use the correct DagCBOR CID encoding in certificates. We might as well use them everywhere.
fixes #18
> Use real CIDs

- gpbft/chain.go
- gpbft/gpbft.go
Change the core GPBFT protocol to:
1) accept QUALITY messages in ant phase or round.
2) update candidate chains at any round or phase based on the initial proposal.
This would permit participants with late-arriving/partially delivered QUALITY messages to affect the candidates chains in CONVERGE phase to sway for the initial proposal or any of its prefixes should there be a strong quorum. No that the changes here do not update the current proposal based on late arriving QUALITY messages.
The changes above, in conjunction with rebroadcast of QUALITY messages introduced in #597 should significantly reduce the likelihood of lack of progress due to partially seen QUALITY messages. See:
- https://github.com/filecoin-project/FIPs/discussions/809
#discussioncomment-10409902
As part of the changes …
> Handle late arriving QUALITY messages in every round

- gpbft/metrics.go
The rebroadcast attempt metric seem to be never used. Remove it.
> Remove unused/duplicate rebroadcast metric

- emulator/driver.go
- emulator/driver_assertions.go
- emulator/host.go
- emulator/instance.go
- emulator/signing.go
- gpbft/gpbft.go
- gpbft/gpbft_test.go
- gpbft/participant_test.go
Fix a bug where if `Host.RequestBroadcast` panics the requested message is never added to the re-broadcast state.
Fix an inconsistent behaviour where error at requested broadcasts via re-broadcast are returned instead of being silently logged.
Enhance emulator to allow pluggable signign logic with two additional signing implementation: erroneous and panic.
Implement tests that assert expected behaviour at signing error or panic.
Fixes #236
> Capture broadcasted messages for re-broadcasting even at panic

- gpbft/ticket_quality.go
- gpbft/ticket_quality_test.go
Test ticket quality
* is weighed by power
* is as expected for edge case power value
* handles unexpected ticket length gracefully
Part of #9
> Unit test ticket quality computation

- gpbft/gpbft.go
- gpbft/ticket_rank.go
- gpbft/ticket_rank_test.go
The Converge ticket selection mechanism previously used the term "quality" to determine which ticket is better where the lower the quality value the better the ticket.
Additionally, the term "quality" is already used in GPBFT for `QUALITY` phase, which is a totally different thing.
To avoid terminology confusion, and for a more intuitive notion in the context of ticket selection use the term "rank" instead, where instead one would say: whichever ticket ranks first is better, i.e. the smaller the value of rank the better the ticket.
While at it, update the docs on the compute function.
> Rename the term Ticket Quality to Ticket Rank for better readability

- emulator/driver.go
- emulator/driver_assertions.go
- emulator/host.go
- gpbft/gpbft_test.go
- gpbft/ticket_rank.go
Test that a participant sways for unseen candidates at `COMMIT` and `CONVERGE`.
Part of #237
> Test sway at commit and converge for unseen candidates

- gpbft/options.go
- gpbft/options_test.go
- manifest/manifest.go
- test/constants_test.go
This fixes part of https://github.com/filecoin-project/go-f3/issues/549 to avoid having the entire network slam pubsub at the same time, although we should still optimize what we rebroadcast.
This also fixes the backoff calculator to return the actual backoff instead of always returning the max (oops).
> Randomize rebroadcast backoff

- gpbft/gpbft.go
- gpbft/gpbft_test.go
This keeps two message lists: one for the current round, one for the previous. With separate fields for quality/decide. That way we don't have to "garbage collect".
This also rebroadcasts newer messages first (except quality, which is always sent first). This _should_ help ensure peers get important messages even if some get dropped in the flood, but I'm not 100% sure?
This fixes the rest of #549, IMO. We may try to rebroadcast a bit more than we need to, but we'll rebroadcast the important messages first.
> refactor: simplify rebroadcast logic and prioritize important messages

- cmd/f3/manifest.go
- go.mod
Resolve the bootstrap addresses, which may be dnsaddrs, before connecting to them in manifest server.
> Resolve bootstrap addresses before connecting in manifest server

- go.mod
- go.sum
v0.1.0 fails to validate a drand signature.
> fix: downgrade kilic/bls12-381 back to v0.1.0

- certstore/certstore.go
- certstore/certstore_test.go
- go.mod
- go.sum
- host.go
I have yet to write any code that cares about intermediate certificates and they can easily be queried with `GetRange`. This change:
1. Makes the certificate subscription system always return the latest certificate, dropping intermediates.
2. Drops the dependency on go-broadcast.
3. Simplifies the code that relies on the certificate subscription logic.
> Simplify CertStore subscriber

- version.json
Bump the version to a full minor version up considering the volume of
changes since the previous release.
> Bump version to `0.3.0` in prep for release

- cmd/f3/run.go
- f3.go
- f3_test.go
- host.go
- internal/writeaheadlog/wal.go
- internal/writeaheadlog/wal_test.go
- wal.go
Pushing the first commit with complete implementation of WAL for peliminary review.
Integration in progress.
> Implement WriteAheadLog

- gpbft/chain.go
- gpbft/chain_test.go
Panicing is perfectly fine in these cases, but not necessary and a little inconsistent (e.g., `Suffix` didn't panic).
1. Avoid panicing when TipSet is nil in Validate.
2. Use nil tipsets as zero tipsets, no need to look at the key. Empty tipset keys will fail `Validate` anyways. Remove `TipSet.Zero`.
3. Return a nil base when the chain has no base instead of panicing.
4. Return a nil head when the chain is empty.
5. Return a nil base chain when the chain has no base.
6. Improve some documentation.
fixes https://github.com/filecoin-project/go-f3/issues/643
> Remove panic cases from TipSet methods and simplify nil handling

- emulator/host.go
- gpbft/api.go
- gpbft/committee.go
- gpbft/committee_test.go
- gpbft/errors.go
- gpbft/mock_host_test.go
- gpbft/participant.go
- gpbft/participant_test.go
- host.go
- sim/adversary/decide.go
- sim/adversary/repeat.go
- sim/adversary/spam.go
- sim/adversary/withhold.go
- sim/host.go
- sim/sim.go
Refactor the `Chain` interface into two separate smaller interfaces for a more pluggable committee caching.
Refactor committee cache out of participant.
This work is part of a larger refactor of validation mechanism and is separated into its own commit for easier review.
Part of #561
> Refactor `Chain` interface into separate do-er interfaces

- gpbft/gpbft.go
- gpbft/gpbft_test.go
- gpbft/options.go
- gpbft/participant.go
- gpbft/participant_test.go
- gpbft/validator.go
- internal/caching/grouped_cache.go
- internal/caching/grouped_cache_test.go
Refactor the validation logic out of `Participant` and into its own dedicated struct that is mutex-free and listens to the progress made by the participant to infer the correct validation path.
The change above significantly reduces the need for mutex control over current instance, which makes it easier to plug in extra conditional behaviour, e.g. #583.
Fixes #561
> Refactor validation logic into a mutex-free pluggable struct

- gpbft/errors.go
- gpbft/errors_test.go
- gpbft/gpbft_test.go
- gpbft/participant.go
- gpbft/validator.go
- host.go
- sim/network.go
- sim/sim.go
- test/withhold_test.go
As a GPBFT instance progresses some messages become irrelevant, in that they do not effectively aid the progress of the instance for participants. Instead, GPBFT offers other built-in mechanisms to aid progress of lagging participants such as selective rebroadcast, propagation of DECIDE messages from the previous instance and finality certificate exchange.
The changes here introduce a dedicated error type returned as part of message validation to signal that although a message is valid it is no longer relevant. This error type is then checked by pubsub to avoid further propagation of those messages.
This reduces the redundant pubsub traffic for the network participants.
Fixes #583
> Drop messages that are no longer useful for GPBFT progression

- gpbft/gpbft.go
- gpbft/participant.go
- gpbft/participant_test.go
- gpbft/progress.go
- gpbft/progress_test.go
- gpbft/validator.go
- host.go
- sim/sim.go
The host implementation needs to know the progress of the current instance for certificate storage and catch up purposes. As a result the current instance must be safe to read from multiple goroutines. This was achieved by a dedicated mutex that synchronised all access to the current instanceID.
Separately, validation logic requires to know how far the current instance has progressed in order to effectively validate incoming messages.
The changes here simplify the locking by unifying the logic for checking the progress of an instance: both validator and host can now get the latest progress from the participant that is safe for concurrent use. This is achieved by moving the progress observer mechanism out of validator and into the participant, while introducing the concept of …
> Simplify participant locking and expose current GPBFT progress

- .github/workflows/go-fuzz.yml
Investigate false negative fuzz test failures due to hitting memory limit by reverting GOGC back to default 100.
Fixes #666
> Reduce GOGC in fuzz tests

- gpbft/participant.go
The `terminatedDuringRound` is unused; remove it.
> Remove the unused `terminatedDuringRound` participant field

- cmd/f3/run.go
- ec/powerdelta_test.go
- f3_test.go
- internal/consensus/fake_ec.go
- internal/powerstore/powerstore_test.go
I need to be able to configure the fake EC to "forget" power tables after some time (and would like to be able to better test power table evolution as well).
Changes:
1. Use functional options (so we can add more later).
2. Make it possible to "forget" power tables after some time.
3. Make it possible to evolve the power-table over time.
> Make the FakeEC more configurable

- emulator/driver.go
- gpbft/participant_test.go
- host.go
- sim/sim.go
We may fail to deliver an alarm if we, e.g., don't have a power table we need to participate in that instance. In that case, we should just wait until we get a finality certificate that'll let us advance to an instance we can participate in.
Also, start the first instance at the correct time (which may be in the future if we're rebooting).
> Don't abort if we fail to deliver an alarm and/or start an instance

- f3.go
- host.go
The root F3 instance holds reference to the `gpbftRunner`, not `gpbftHost`. To allow access to current progress from Lotus, move the `Progress` implementation to runner and expose at root `F3` type.
Part of #599
> Expose access to progress on f3 runner

- gpbft/message_builder.go
- sim/host.go
- sim/network.go
The interface`SignerWithMarshaler` is only used by `sim` package. Remove it from top level `gpbft` package into unexported `sim` network implementation.
Unexport simulation `NetworkFor` since it is returning an unexported type.
> Move redundant top-level singer-marshaller interface

- manifest/manifest.go
I can't recall if we've made any major breaking changes, but I want to bump this one more time before the final release just to be safe.
> Bump the protocol version compatibility

- manifest/manifest.go
- From testing, we need a 6s delta.
- This configures the alignment to be 15s which is what we used in testing.
- It adjusts the rebroadcast timings to align with the new delta.
> Update manifest defaults for mainnet

- cmd/f3/observer.go
- cmd/f3/run.go
- f3_test.go
- manifest/dynamic_provider.go
- manifest/dynamic_test.go
That way we can, e.g., prevent the manifest server from sending manifests that apply to the mainnet network name, actually finalize tipsets, etc.
See #688.
> Support filtering received dynamic manifest

- host.go
- manifest/manifest.go
This'll make it easier to wire up the bootstrap logic.
> Specify whether or not to finalize tipsets in the manifest itself

- manifest/fusing_provider.go
Unfortunately, due to https://github.com/filecoin-project/lotus/issues/12557, time in our lotus tests is basically broken. So we start by relying on time but also check the head so we don't switch too early.
This doesn't matter in practice, but I'd really like to be able to test this in CI, fully integrated.
> Delay static manifest until our head is within the target period

- f3.go
- f3_helpers_test.go
- f3_test.go
That way we:
1. Stop immediately.
2. Expose the manifest to the user immediately so they can see which network we're going to participate in (important for the miner participation API).
> Apply manifest update immediately after receipt

- f3_test.go
[Repeated runs on CI](https://github.com/filecoin-project/go-f3/pull/700#issuecomment-2399531652) shows that there is some contention when `f3_test.go` tests are run in parallel. See #700. Avoid F3 test flakiness by running them serially.
This fixes the symptom that is test flakiness but not the root cause. The root cause may be within one of the test dependencies.
Compared to `main` the changes here don't make much difference in terms of the length of time it takes for CI to run the tests.
Fixes #623, #659, #684, #699
> Do not run F3 tests in parallel

- f3.go
- host.go
Respect the given context when broadcasting messages in F3 instead of using the internal running context.
> Use the given context on F3 broadcast message

- sim/signing/fake.go
Running `make lint` locally highlights these lint issues which is slightly annoying. Explicitly ignore the error to silence the linter.
> Fix golangci-lint warnings since it is still used in `make lint`

- f3.go
- store.go
This PR adds more F3 startup logs for easier troubleshooting.
After the change:
```
...
2024-10-15T13:15:14.693+0800    INFO    f3      go-f3/store.go:50       loaded initial power table at epoch 1860: bafy2bzaced6vgp6agebcyymrmh3q2r6gmiz3owb2b7kz5h744u7frlkdpg3qy
...
2024-10-15T13:15:14.704+0800    INFO    f3      go-f3/f3.go:200 F3 is starting  {"initialDelay": 0, "hasPendingManifest": false, "NetworkName": "butterflynet", "bootstrapEpoch": 2760, "finality": 900, "initialPowerTable": "b"}
```
> chore: add more logs on manifest and initial power table

- host.go
When bootstrapping a Forest or Lotus node from scratch with the latest snapshot (mostly on CI), F3 downloads certificates from instance 0 and floods stdout with tons of `skipping forwards based on cert`. 
This PR proposes demoting its log level to DEBUG as it does not seem to be as important as other INFO logs under `f3`.
> fix(log): demote log level to DEBUG on skipping forwards based on cert

- cmd/f3/certs.go
- cmd/f3/main.go
Implement command to get certificates from a specific peer using the cert exchange protocol and optionally list power table entries for the first certificate listed.
> Implement command to list power table and  certificates form a peer

- internal/powerstore/powerstore.go
- internal/powerstore/powerstore_test.go
> Fix an off-by-one in the powerstore

- f3.go
- internal/powerstore/powerstore.go
- internal/powerstore/powerstore_test.go
Reverts filecoin-project/go-f3#740
The data in the OhShitStore™ looks correct on Archioz.
> Revert "Rename OhShitStore™ to `powerstore`"

- certexchange/polling/poller.go
- certs/certs.go
- certs/certs_test.go
- host.go
The finality certificate APIs at times switch between pointer and values. This introduces the need for extra gymnastics when validating certs, where a slice of cert pointers need to be converted to values to use the cert verification APIs.
Instead, consistently accept pointers to certs.
> Consistently use cert pointer in verification

- .github/workflows/go-test.yml
This is a follow-up to the discussions we've been having at https://ipdx-workspace.slack.com/archives/C03KLC57LKB/p1730963666791569
I forgot about this limitation before. In this PR I pointed the go-test at the fork of https://github.com/ipdxco/unified-github-workflows that lives in filecoin-project org https://github.com/filecoin-project/unified-github-workflows. By doing that, we'll be able to set up custom runners for the workflow via the repo config vars.
What's also worth noting is that https://github.com/filecoin-project/unified-github-workflows is kept up-to-date automatically by https://github.com/ipdxco/unified-github-workflows/actions/workflows/sync-forks.yml (so it doesn't introduce any additional manual maintenance burden whatsoever).
> ci: allow custom runners usage in the Go Test workflow

- internal/consensus/fake_ec.go
Generate a unique bacon per each tipset created by fake ec for better testing.
> Generate unique beacon per each fake EC tipset

- certs/certs.go
- gpbft/chain.go
- gpbft/chain_test.go
- gpbft/gpbft.go
- gpbft/gpbft_test.go
🤷 is this OK to do here?
Basically: the byte form of a TipSetKey isn't very useful as a consumer of the Lotus API, we don't give it like that anywhere. So a user would have to decoded the base64 bytes, extract the CIDs from it using one of the CID libraries, then re-form it back into the array-of-CIDs dag-json form to post it back to a Lotus API to do anything with it (like calling `ChainGetTipSet`).
Before:
```
$ curl -s -X POST -H "Content-Type: application/json" --data '{"method":"Filecoin.F3GetLatestCertificate","params":[],"id":2,"jsonrpc":"2.0"}' http://127.0.0.1:1235/rpc/v1
{"id":2,"jsonrpc":"2.0","result":{"GPBFTInstance":42292,"ECChain":[{"Epoch":2175657,"Key":"AXGg5AIgSRY8LQrdggB5IOtuEPM7t3QVCZsQd6X6w6ZGM6e0AE4BcaDkAiA3gbWY6IFo8bRTc+9TKGlmCEU+bgNQzpoNVhhEr/ySswFxoOQCICxs2tKsVpIAi …
```
> Custom JSON serialization of TipSetKey for array-of-CIDs

- host.go
Closes: https://github.com/filecoin-project/go-f3/issues/760
I think this reflects the intent of the code.
> Minor log msg adjustment for passive testing finalization skip

- gpbft/metrics.go
Add the missing custom tag for `ErrValidationNotRelevant` type as `invalid_not_relevant`.
> Tag validation errors for non-relevant messages

- cmd/f3/observer.go
Implement the ability to configure lower and higher watermarks for
Observer connection manager.
This is to allow high connectivity for the observer to aid a more
effective F3 message observation.
> Make Observer connection manager watermarks configurable

- host.go
Log backoff duration at instance start as DEBUG.
Relates to #770
> Reduce log verbosity when computing instance start

- host.go
Increase the pubsub and internal message queue buffer sizes to 128. This is to allow a larger headroom for buffered messages if the internal message handling loop is too slow, or in a case where there is a slight missalignment across nodes on bootstrap.
Fixes #759
> Increase message and subscription buffer size to 128

- version.json
Bump version in prep for `v0.7.3` release.
> Bump version in prep for `v0.7.3` release

- observer/observer.go
Use a pubsub message ID function consistent with gpbft pubsub settings.
> Set GPBFT message ID function in observer

- consensus_inputs.go
- go.mod
- host.go
First commit is a refactor, second one is the change.
> Introduce caching of PowerTable CIDs

- consensus_inputs.go
- f3_test.go
- gpbft/chain.go
- internal/powerstore/powerstore_test.go
- manifest/manifest.go
- manifest/manifest_test.go
> feat: add ChainProposedLength into the manifest

- certstore/certstore.go
- f3.go
- f3_test.go
- gpbft/gpbft.go
- internal/powerstore/powerstore.go
- manifest/manifest.go
> Consistently use lower case for errors with no ending punctuation

- .github/workflows/publish-ghcr.yml
This repository started using unified CI (uci) a while back to make tagged releases. This release mechanism is triggered by editing the `version.json` which in turn triggers a CI workflow to make a tagged release along with ghithub release etc.
The issue with this approach is that because the tag is created by CI it does not trigger other CI jobs that listen to `tags: ['v*']` events. Therefore, since the switch we have only been publishing containers tagged with `main`.
The changes here resolve this issue by triggering the GHCR publish workflow whenever releaser wrokflow succeeds. It then fishes out the ref produced by the releaser workflow to use as tagging. This will then give us containers tagged by whatever release we make using uci releaser workflow.
Additionally, it adds …
> Publish containers tagged with version created by uci releaser

- .github/workflows/publish-ghcr.yml
For debugging purposes we need to be able to deploy a specific commit as observer or manifest server without having to cut a release or even merge to `main`.
> Add the ability to publish container for specific commit sha

- f3_test.go
- go.mod
- host.go
- manifest/manifest.go
- msg_encoding.go
- msg_encoding_test.go
Add the ability to compress GPBFT messages controllable via manifest. Implement benchmarks to compare vanilla CBOR and ZSTD encoding.
Basic local run:
```
BenchmarkCborEncoding-12    	   47173	     25491 ns/op	  135409 B/op	      87 allocs/op
BenchmarkCborDecoding-12    	   64550	     18078 ns/op	   61728 B/op	     209 allocs/op
BenchmarkZstdEncoding-12    	   29061	     41489 ns/op	  193455 B/op	      88 allocs/op
BenchmarkZstdDecoding-12    	   66172	     17924 ns/op	  176517 B/op	     211 allocs/op
```
Fixes #786
> Implement GPBFT message compression using zstd

- chainexchange/chainexchange.go
- chainexchange/options.go
- chainexchange/pubsub.go
- chainexchange/pubsub_test.go
Expand chain exchange to accept a listener which is notified whenever a new chain is discovered. This mechanism is intended to be integrated into F3 host pubsub, whereupon receiving a partial message the host looks up its chain. When known, the chain is returned immediately. Otherwise, the host would buffer the partial message and await notification of its discovering from chain exchange.
Part of #792
> Add the ability to listen for discovered chains

- f3_test.go
Use `Progress` to assert the current instance and add utility to print change across test F3 nodes useful for debugging.
> Simplify current instance assertion and add test status utility

- host.go
Avoid referencing subscription when constructing an error message as it may be nil when subscription fails.
> Fix potential panic when subscribing to topic fails

- host.go
- merkle/merkle.go
- partial_msg.go
- partial_validator.go
When messages arrive with yet to be discovered EC chain we want to do as much validation as possible before buffering the message for future use.
Because the key of the EC chain is included in the partial messages we are able to validate basically everything about the message except the chain itself. The changes here implement this ability.
The implementation introduces a new validator implementation specifically written to handle partial messages. The validation rules are similar to the full GMesssage validator but then are adopted to infer the state of a message from chain key instead. A separate issue is captured to reduce duplicate rules across the two validators. This refactor is postponed on purpose as it touches a lot of the core implementations. Instead, the implementation here …
> Implement validation for buffered partial messages

- gpbft/chain.go
- gpbft/chain_test.go
The `ECChain` API offers a few functions that seem to only have been used in unit testing the functions themselves.
Remove them to reduce LOC, in favor of adding back later if ever anyone asked for it.
> Reduce the `ECChain` API surface by removing unused capability

- gpbft/cbor_gen.go
- gpbft/chain.go
- gpbft/gpbft.go
The cbor-gen does not seem to implicitly enforce the length specified in the underlying Golang array type. Instead, it uses the maximum number of allowed bytes if no `maxlen` struct tag is specified (2MiB).
Strictly enforce the max allowed size to avoid potential attack vector.
Relates to:
* https://github.com/whyrusleeping/cbor-gen/pull/106
> Strictly enforce the Commitments max size in CBOR

- chainexchange/pubsub.go
Add `ECChain` validation to chain exchange pubsub validation function to reject invalid chains as early as possible.
Change the ordering of validation rules such that cheaper checks are done first before checking current progress.
> Check the validity of ECChain first in chain exchange

- chainexchange/cbor_gen.go
- chainexchange/chainexchange.go
- chainexchange/options.go
- chainexchange/pubsub.go
- chainexchange/pubsub_test.go
- gpbft/chain.go
- gpbft/chain_test.go
- manifest/manifest.go
- partial_msg.go
Based on a configured rebroadcast interval periodically rebroadcast the longest chain currently being progressed by GPBFT.
Extend the chain exchange broadcast message to include a timestamp rounded down to the rebroadcast interval as a way to work around gossipsub deduplication. This is to help gain better message propagation.
The rebroadcast interval is reset as soon as the first message with a larger instance is observed, signaling the start of the next instance. This helps synchronize the chain rebroadcast intervals relative to the GPBFT instance start.
Fixes #814
> Add a periodic chain re-broadcast mechanism

- chainexchange/pubsub.go
- f3_test.go
- host.go
- partial_msg.go
Once a decision about an instance is received, remove all states related to the older instances from partial message manager and chain exchange.
Part of #792
> Clear out old instances from partial message management

- Dockerfile
There is no reason not to use a more recent version of go to build the binary in docker images.
This should also reduce the chances of random segmentation fault when building for arm64 platform.
Fixes #846
> Use go 1.23 in docker images

- encoding_bench_test.go
- internal/encoding/encoding.go
Pool the decode buffers and set strict max cap allocation for zstd decompressor.
See Benchamark results below.
Before:
```
BenchmarkCborEncoding
BenchmarkCborEncoding-12    	  467352	      2376 ns/op	   14680 B/op	      10 allocs/op
BenchmarkCborDecoding
BenchmarkCborDecoding-12    	  104410	     11347 ns/op	   14944 B/op	      27 allocs/op
BenchmarkZstdEncoding
BenchmarkZstdEncoding-12    	  286735	      3897 ns/op	   46748 B/op	      12 allocs/op
BenchmarkZstdDecoding
BenchmarkZstdDecoding-12    	  110794	     10783 ns/op	   28512 B/op	      28 allocs/op
```
After:
```
BenchmarkCborEncoding
BenchmarkCborEncoding-12    	  436754	      2383 ns/op	   14680 B/op	      10 allocs/op
BenchmarkCborDecoding
BenchmarkCborDecoding-12    	  106809	     11280 ns/op	   14944 B/op	      27 allocs/op …
```
> Pool decode buffers when encoding messages using compression

- chainexchange/metrics.go
- chainexchange/pubsub.go
- host.go
- internal/measurements/attributes.go
- metrics.go
- partial_msg.go
Add metrics that measure various aspects of chain exchange and partial messages, including:
* The number of messages pending partial messages.
* The total number instances with a partial message.
* The chain exchange broadcast count.
* The length of broadcast chain.
* The time spent on chain exchange validation.
* Qualify existing GPBFT validation metrics with partial message attribute.
* The number of duplicate partial messages qualified with equivocation attribute.
Fixes: #812
> Add chain exchange and partial message metrics

- manifest/manifest.go
Bump the manifest version compatibility to 5 to avoid any accidental participation of old lotus versions considering the changes introduced since v4.
Relates to #858
> Bump the manifest version compatibility to 5

- internal/measurements/attributes.go
Explicitly tag errors of kind pubsub validation error for most popular/important cases.
This is to distill false-negatives in metrics collected as part of chain exchange.
> Expand metrics status tags with pubsub validation error types

- partial_msg.go
When an entire instance is evicted from partial message buffer, decrement the number of total messages in the buffer by the partial messages of that instance.
> Decrement the count of partial messages when instance is removed

- cmd/f3/manifest.go
- manifest/dynamic_provider.go
- manifest/manifest.go
- manifest/manifest_test.go
Introduce Manifest CID calculation and log it both at manifest publisher and manifest receiver for better debugging.
> Determine the manifest CID and log it for better debugging

- chainexchange/pubsub_test.go
- gpbft/gpbft.go
Since ECChain is changed to pointer at struct level log the proposal and vale directly. Otherwise, we get memory address to pointer in logs.
> Fix GPBFT Trace log logging by pointer

- host.go
It is printed per finalised instance, which is too verbose during passive testing.
> Reduce log level of skipping finalization message to DEBUG

- internal/encoding/encoding.go
- internal/encoding/encoding_api_test.go
- internal/encoding/encoding_test.go
- internal/encoding/metrics.go
Add metrics to measure time spent on encoding CBOR+ZSTD, and the compaction ratio achieved by ZSTD.
Fixes #863
> Measure time spent on encoding and the compaction ratio

- internal/encoding/encoding.go
- internal/encoding/metrics.go
Tag the encoding time measurements with success/failure.
Fixes inconsistent error check across `defer` statements measuring time.
> Tag status in encoding time metrics

- internal/encoding/encoding.go
Calculate the max encoded size based on the uncompressed data size and use it as the capacity of the buffer to which data is encoded.
Benchmark comparison (10 repetitions):
```
$ benchstat before.txt after.txt
│ before.txt  │              after.txt              │
│   sec/op    │   sec/op     vs base                │
ZstdEncoding-12   3.949µ ± 6%   3.375µ ± 2%  -14.55% (p=0.000 n=10)
ZstdDecoding-12   10.60µ ± 1%   10.56µ ± 2%        ~ (p=0.143 n=10)
geomean           6.470µ        5.970µ        -7.72%
│  before.txt  │              after.txt               │
│     B/op     │     B/op      vs base                │
ZstdEncoding-12   45.84Ki ± 0%   27.83Ki ± 0%  -39.29% (p=0.000 n=10)
ZstdDecoding-12   17.96Ki ± 1%   18.01Ki ± 1%        ~ (p=0.315 n=10)
geomean           28.69Ki        22.39Ki …
```
> Pick an optimal zstd encoding buffer based on uncompressed data size

- certstore/certstore.go
- certstore/certstore_test.go
Certificate store already keeps track of the latest power table, i.e., the power table of the next expected certificate. Use this pre-computed table whenever the next power table is asked for instead of re-computing it every time.
This results in a much faster response to `GetPowerTable` for the most common case: getting the committee as part of monotonic progress of GPBFT instances.
Fixes #881
> Use the latest computed power table instead of always ranging certs

- version.json
Considering F3 has been running on butterflynet for a while and to unblock the Lotus bubble-up PR cutting a release pre-emptively.
There will most likely be further go-f3 releases prior to calibnet and mainnet upgrades.
Bumped the version straight to `v0.8.0` considering the breadth of changes in chain exchange, and partial message propagation.
> Bump version in prep for release

- manifest/manifest.go
- manifest/manifest_test.go
Since the introduction of partial GPBFT messages change the topic and bump the manifest version to avoid overlap in having different message formats on the same topic entirely.
Fixes #887
> Change GPBFT topic to avoid message format clash

- partial_validator.go
Return a partially validated message when the message is present in the validation cache.
* Thanks to @parthshah1 for pointing this issue out 🙏 
* Originally reported by Antithesis.
> Fix nil pointer return on already validated partial message

- metrics.go
- partial_msg.go
When partial message buffer or chain broadcast buffer is full the local participant must be too slow in processing them. This means the chances are it is behind. When a participant is behind, then, the chances are that later messages are more useful in getting it to catch up compared to earlier ones, because of the skipping (round/instance) mechanism built into GPBFT.
Add metrics to measure the number of dropped messages by kind.
Part of #893
> Prefer dropping earlier messages when buffer is full

- host.go
- manifest/manifest.go
- manifest/manifest_test.go
Parameterise the buffer size for the gmessage subscription passed to pubsub, and the channel of validated messages to which messages are written for processing by gpbft.
This is to cover all the corners in prep for mainnet passive testing, since in the past we have had to bump thes values due to slow processing of messages in specific cases.
> Parameterise F3 runner pusub constants into manifest

- manifest/manifest.go
- partial_msg.go
- partial_msg_test.go
Fix a bug where timestamp calculation was not respecting the time precision, and using unit inconsistently.
Consistently use millisecond time precision and add tests.
While at it fix the missing manifest validation for interval and age.
Part of : #893
> Fix chain broadcast interval timestamp calculation

- metrics.go
- partial_validator.go
Add metrics to measure the partial validation cache hit vs miss for messages and justifications.
> Add metrics to measure partial validation cache hit/miss

- f3_test.go
- host.go
- manifest/manifest.go
- manifest/manifest_test.go
- partial_msg.go
Just to make sure we have inverted the control to change these at runtime via passive testing, parameterize all the constants in partial message manager in manifest.
This should allow us to investigate any potential effect of congestion that could result in dropping messages.
Part of #893
> Parameterise all partial message manager config in manifest

- manifest/manifest.go
- manifest/manifest_test.go
Considering the set of newly added params, bump the compatibility version to avoid accidental manifest acceptance by old code.
> Bump manifest compatibility version to 7

- chainexchange/pubsub.go
- chainexchange/pubsub_test.go
The work in #904 standardized the chain exchange timestamp to millisecond. But the change wasn't bubbled up consistently to chain exchange pubsub validator.
Use millisecond time for comparison, add logging for better visibility.
Fix the tests to reflect the change, and while at it refactor the test into table test.
> Fix bug in chain exchange timestamp validation time unit

- manifest/manifest.go
- manifest/manifest_test.go
The data shows average of 1.5x reduction in message size on 2k network for partial gmessage sizes.
Based on the testing, so far it's harmless and beneficial to have compression on gmessage topic enabled.
> Enable zstd compression on gmessage topic by default

- chainexchange/options.go
- chainexchange/pubsub.go
- chainexchange/pubsub_test.go
- gpbft/chain.go
- gpbft/chain_test.go
- host.go
- internal/clock/clock.go
- merkle/merkle.go
- merkle/merkle_test.go
- partial_msg.go
- sim/signing/fake.go
Adjust the for loop not to repeat the full chain
The EqualExportedValues is required as we never call explicit Key these
values, leaving cached key empty.
Resolves #831
> feat: batch computation of ECChain Keys in chainexchange

- chainexchange/pubsub_test.go
Add tests that assert:
* pubsub validation correctness
* swarm chain discovery with bound cache size
* eviction of instances
* notification completeness
Part of #869
> Improve test coverage of chain exchange package

- f3_test.go
- internal/consensus/fake_ec.go
- internal/consensus/fake_ec_test.go
Implement a mechanims to configure the fake EC to fork away in a reproducible way.
Add tests that configure 2 nodes with different ECs that fork away from one another and assert that they finalize.
Fixes #869
> Implement forking fake EC and test chain exchange

- merkle/merkle.go
- merkle/merkle_test.go
Implement memoization and propoage hashers manually.
Overall improvement:
```
name                         old time/op    new time/op    delta
Prefixes/IndividualPrefix-8    9.91ms ± 7%    8.17ms ± 6%  -17.56%  (p=0.000 n=10+10)
Prefixes/BatchPrefix-8         3.43ms ± 6%    0.64ms ± 3%  -81.26%  (p=0.000 n=10+10)
name                         old alloc/op   new alloc/op   delta
Prefixes/IndividualPrefix-8    4.54MB ± 0%    1.11MB ± 0%  -75.66%  (p=0.000 n=10+10)
Prefixes/BatchPrefix-8         1.61MB ± 0%    0.22MB ± 0%  -86.65%  (p=0.000 n=8+10)
name                         old allocs/op  new allocs/op  delta
Prefixes/IndividualPrefix-8     33.4k ± 0%     33.7k ± 0%   +0.95%  (p=0.000 n=10+10)
Prefixes/BatchPrefix-8          11.8k ± 0%      2.5k ± 0%  -78.73%  (p=0.000 n=10+10)
``` …
> merkle: further hashing opimizations

- gpbft/gpbft.go
Fix a bug where current round gauge value was only being updated on skip to round and next round, which effectively measured the max round not current.
> Reset current round gauge to zero at start

- manifest/manifest.go
Otherwise the only valid value was chain exchange max length equal to
proposal chain length
Fixes https://github.com/filecoin-project/go-f3/issues/941
> fix: validate chain proposal length against chain exchange max length

- manifest/manifest.go
Simply require the timestamp age to be more than 1 ms. 4X of chain rebroadcast interval is unnecessarily unflexible.
> Remove chainx validation rule between max age and rebroadcast interval

- host.go
- metrics.go
Meter the time spent on EC checkpointing tagged by status.
Relates to https://github.com/filecoin-project/go-f3/issues/960
> Add metrics to measure the time spent on EC checkpointing

- gpbft/gpbft.go
- partial_validator.go
Grow the buffer prior to marshaling the payload for signing to reduce allocations.
Reduce the duplicate code for marshaling logic between payload type and partial validation.
> Grow payload signing buffer before marshaling and reduce duplicate code

- certchain/certchain_test.go
- cmd/f3/run.go
- ec/powerdelta_test.go
- f3_test.go
- internal/consensus/fake_ec.go
- internal/consensus/fake_ec_test.go
- internal/consensus/options.go
- internal/consensus/tipset.go
- internal/powerstore/powerstore_test.go
Refactor fake EC to use the existing options it has to take a fake clock with fallback to a real clock if none is specified.
Separate the code in different files to reduce LOC in the core fake ec logic.
> Refactor fake EC to take clock as option

- cmd/f3/aider.go
- cmd/f3/main.go
- observer/model.go
- observer/observer.go
Implement a utility that:
* finds the latest instance and round
* reconstructs the list of all known messages that would have been re-broadcasted by the network from observer server.
* broadcasts it to the entire network.
...with configurable interval and degree of parallelism.
The aider additionally uses a list of give lotus nodes to find peers in the network. It then periodically connects to them to maximise its connectivity and therefore message propagation.
> Implement an aider utility to help rebroadcast using observer

- observer/schema.sql
Without this if type exists observer will fail to execute schema
> Gracefully handle alteration to observer schema

- observer/schema.sql
Without it the db creation fails on service restart if db exists.
> Fix missing if not exist in observer table migration

- cmd/f3/aider.go
- internal/lotus/net.go
Determine if F3 is lagging and if so engage rebroadcast aid with resilience against failure cases. The lag determination strategy uses both lotus daemon and observer as sources to determine the current F3 progress. It then decides if F3 is lagging behind based on:
* number of rounds
* distance from head
* elapsed time since instance ID changed.
* last successful lag determination
The combination of above assures that both in cases of failure or less than perfect information aid is attempted. The only case where aid can't be attempted is when no initial F3 state is determinable.
Fixes #988
> Implement lag awareness in aider based on current progress

- cmd/f3/observer.go
- observer/observer.go
- observer/options.go
For fast batch insertion of messages observed into duckdb, use the native appender to batch the messages based on size or max wait time. Whichever happens first.
Fixes #993
> Batch insert observed messages using Duckdb appender

- manifest/manifest.go
Part of filecoin-project/lotus#12971
This pull request removes dead code related to equality checks in the manifest package for cleanup and improved maintainability. Key changes include:
- Removal of the unused slices import.
- Deletion of the EcConfig.Equal method.
- Deletion of the Manifest.Equal method.
> delete dead Manifest.Equal code

- emulator/driver.go
- emulator/host.go
- gpbft/gpbft.go
- gpbft/gpbft_test.go
- gpbft/options.go
The original GPBFT protocol dictates that the rebroadcast only gets triggered after the phase timeout has expired. This is reasonable for low number of rounds, where the vast majority of instances finalize within a single round. However, there is an edge-case where when an instance enters more than a few rounds the exponential increase of phase timeout results in extended periods of total radio silence.
As a result, the state propagation is hindered greatly, which in turn increases the chances of the instance taking even longer to finalize.
The changes here introduce a threshold at which rebroadcast is scheduled without waiting for phase timeout to expire first (defaulting to 3). In this design, the rebroadcast and successive rebroadcasts work exactly the same way as dictated in GPBFT …
> Rebroadcast immediately once a round threshold is met

- gpbft/validator_api_test.go
- gpbft/validator_test.go
The work here introduces a new testing machinery that can accept a scenario along with custom messages for asserting fine-grained validation rules.
The actual test case is being tested, however, is limited to the scope of #1018.
Fixes #1018
> Add message signature validation test for partial and non-partial

- observer/model.go
- observer/schema.sql
Remove the primary key constraint in finality certs in observer to avoid an edge-case where multiple certs for the same instance may be discovered in conjunction with using duckdb appender to insert them.
Appender does not offer the ability to insert or ignore records. And even if it did, we probably want to capture all and any certs, since certs are validated before insertion.
While at it, also fix a typo in cert JSON struct tags.
> Remove finality cert table constraint in observer

- observer/observer.go
We need to swap them becasue the wildcard seems to be avaluated at the
view creation time.
> fix(aider): use replace to swap out the messages view

- cmd/f3/observer.go
- observer/observer.go
- observer/options.go
This adds a new flag to the observer command to limit the size of the
rotated files. When the rotated files exceed this size, the oldest files
are deleted.
This is in support of https://github.com/filecoin-project/go-f3/issues/1041
> feat: Add retention size limit for rotated files

- certs/certs.go
- certstore/snapshot.go
The `sort` operation in `ApplyPowerTableDiffs` turns out to be expensive. 
This PR introduces another `func ApplyPowerTableDiffsToMap(powerTableMap map[gpbft.ActorID]gpbft.PowerEntry, diffs ...PowerTableDiff) (map[gpbft.ActorID]gpbft.PowerEntry, error)` to avoid sorting.
It also adds more validations against first instance, latest instance and powertable cid.
Perf stats of importing a mainnet F3 snapshot on my laptop show ~99% perf gain
```
0.884s
0.773s
0.864s
86.547s
88.422s
86.998s
```
> fix: improve performance of ApplyPowerTableDiffs in ImportSnapshotToDatastore

- Dockerfile
- go.mod
This reverts commit f6bae221d349fb00210fa2501e90373f14090b57.
We need go.mod with 1.23 for Lotus
> Revert "ci: uci/update-go (#1048)"
